- components/chef-run/lib/chef-run/target_resolver.rb
- components/chef-run/spec/unit/target_resolver_spec.rb
Always expand host to include full user info
To provide a consistent experience with multi- and single-target,
we will always construct a fully qualified url in the form:
proto://user-info@target
Where user-info is "username:password" (ref: RFC 3928[1])
We no longer pass the user or password option into train, so that there
is no conflict between those values and the values embedded in the url.
This ensures that train will only have one set of credentials to work
with per host, and won't do surprising things.
A blank username will be expanded in the form ":password@host.com" and
a blank password will be supplied in the form "username:@host.com", both
of which are valid under the RFC.
This fixes github issue #175
> [SHACK-212] [GH #175] Always expand host to include full user info

- components/chef-run/bin/chef-run
- components/chef-run/i18n/en.yml
- components/chef-run/lib/chef-run/cli.rb
- components/chef-run/lib/chef-run/config.rb
- components/chef-run/lib/chef-run/startup.rb
- components/chef-run/spec/integration/spec_helper.rb
- components/chef-run/spec/unit/cli_spec.rb
- components/chef-run/spec/unit/startup_spec.rb
In order to ensure that all configuration is loaded before we populate CLI options via Mixlib::CLI, 
this change separtes o
This resolves #180, in which changed configuration values were not recognized by the CLI when they were referenced before loading configuration - resulting in default values being propagated through the system. 
Changes: 
- Move tasks related to setup or initialization into a new Startup class
- chef-run executable now invokes Startup.run, which hands off control to CLI after all startup tasks are complete.
> [SHACK-210] [GH #180] Perform startup tasks outside of main CLI handling

- components/chef-run/i18n/en.yml
- components/chef-run/lib/chef-run/cli.rb
- components/chef-run/lib/chef-run/config.rb
- components/chef-run/lib/chef-run/target_resolver.rb
- components/chef-run/spec/integration/fixtures/chef_help.out
- components/chef-run/spec/unit/target_resolver_spec.rb
Not all customers use ssh for the majority of their hosts.
Currently, the only alternative we give is to require
the 'winrm://' prefix for each target.  This change adds
the flag --protocol to apply to all targets, and adds the
connection.default_protocol option
NOTE: the command line flag will work with this PR, but the configuration option 
will not work before #180 is fixed and merged. 
Fixes #178 
> [SHACK-213] [GH-178] Add --protocol flag

- components/chef-run/i18n/en.yml
- components/chef-run/lib/chef-run/startup.rb
- components/chef-run/spec/unit/startup_spec.rb
When an invalid configuration option is set in the config toml, an error spews forth: 
```
bundler: failed to load command: chef-run (/home/marc/.gem/ruby/2.5.0/bin/chef-run)
Mixlib::Config::UnknownConfigOptionError: Cannot set unsupported config value bob.
/home/marc/.gem/ruby/2.5.0/gems/mixlib-config-2.2.6/lib/mixlib/config.rb:597:in `internal_set'
/home/marc/.gem/ruby/2.5.0/gems/mixlib-config-2.2.6/lib/mixlib/config.rb:626:in `internal_get_or_set'
/home/marc/.gem/ruby/2.5.0/gems/mixlib-config-2.2.6/lib/mixlib/config.rb:556:in `method_missing'
--snip--
```
This shows something more helpful, and more inline with our UX requirements: 
```
Invalid configuration entry.
When loading '/home/marc/.chef-workstation/config.toml',
the …
```
> [SHACK-195] Handle bad configuration errors gracefully.

- components/chef-run/lib/chef-run/cli.rb
- components/chef-run/spec/integration/fixtures/chef_help.out
We were incorrectly passing the config value for
'default_protocol' into TargetResolver, but it we capture it
under the key 'protocol'
> Pass correct config value for protocol

- components/chef-run/lib/chef-run/config.rb
- components/chef-run/spec/unit/config_spec.rb
When the default configuration file is deleted, and
a custom file is not specified, chef-run emits a stack trace
due to failure loading the missing file.
This can happen when the customer deletes or removes the default
config.toml. chef-run creates the file only on first-run, so if it's
removed after that point it stays gone.
Because we have to assume the customer had a reason for deleting the
configuration file, we can't recreate a new empty file.  Instead,
this fix changes it so that if the config file is missing, we don't try
to load it. This will leave configuration defaults in place.
* n/a
> Fix error that occurs when config file deleted.

- components/chef-run/i18n/en.yml
- components/chef-run/lib/chef-run/cli.rb
- components/chef-run/lib/chef-run/temp_cookbook.rb
- components/chef-run/lib/chef-run/ui/error_printer.rb
- components/chef-run/lib/chef-run/ui/terminal.rb
- components/chef-run/spec/unit/cli_spec.rb
- components/chef-run/spec/unit/temp_cookbook_spec.rb
When converging a recipe in an existing cookbook we don't want to blow
away a possible existing Policyfile because it could have custom sources
configured.
SHACK-233
> [SHACK-233] Do not overwrite existing Policyfile

- components/chef-run/lib/chef-run/config.rb
This must have gotten deleted at some point. Adding it back ensures we load any local `~/.chef/knife.rb` or `/etc/chef/client.rb` on user's workstation
> We should be loading default config using workstation config loader

- components/chef-cli/lib/chef-cli/config.rb
- components/chef-run/lib/chef-run/startup.rb
This change adds the requisite `mkdir` commands to make sure the directory exists before attempting to write under it. Note—I didn't copy the “unless exist” clause as used in the integration tests because `mkdir` is idempotent and I trust it's actually less expensive without our condition.
Attempting to run these programs without `~/.chef-workstation` already created results in a Ruby stack trace as it fails to write a config file to that path.
```
+$ chef-run
Creating config file in /home/trevor/.chef-workstation/config.toml.
Traceback (most recent call last):
11: from /usr/bin/chef-run:179:in `<main>'
10: from /usr/bin/chef-run:179:in `load'
9: from /opt/chef-workstation/embedded/lib/ruby/gems/2.5.0/gems/chef-run-0.1.133/bin/chef-run:23:in `<top (required)>'
8: from …
```
> Create ~/.chef-workstation before config file

- ci/verify.bat
- ci/verify.sh
Our pipeline is passing `chef-run version` when it should not be.
N/A
Signed-off-by: tyler-ball <tyleraball@gmail.com>
> Our verify scripts should fail the pipeline if any of our commands fail

- .github/PULL_REQUEST_TEMPLATE.md
PR titles are included in the CHANGELOG autogenerated by this project's pipeline. So, good PR titles feed into good CHANGELOG entries. Here's a reminder to PR authors to review the language of the title.
Note, this PR is not intended to be included in the CHANGELOG.
> 🌈 add reminder in PR template for a quality title ✨

- omnibus/config/projects/chef-workstation.rb
This pins the ChefDK to the 3.1 release branch (https://github.com/chef/chef-dk/pull/1611). The builds are currently failing with Nokogiri 1.8.3, but rolling back to 1.8.2 temporarily will allow us to clear up the pipeline and get Workstation builds flowing again.
Jira SHACK-278
> [SHACK-278] Pinning ChefDK until we can successfully update Nokogiri

- components/chef-run/lib/chef-run/ui/terminal.rb
- components/chef-run/spec/unit/ui/terminal_spec.rb
> [SHACK-280] Multi-host spinner correctly displays hostnames again

- .expeditor/config.yml
This reverts commit bdd19e24a89419750b0bd853cfde5d3eb3b0cb61. Some kinks
to be worked out in expeditor's buffer support before we can enable.
Fixes build pipeline SHACK-283
> Revert "Adding expeditor buffers" to fix pipeline

- components/chef-run/i18n/en.yml
- components/chef-run/lib/chef-run/target_host.rb
- www/site/content/docs/chef-workstation/troubleshooting.md
This handles the error 'Your SSH Agent has no keys added...' out of
train, and exposes it as CHEFTRN007 which contains instructions to
remedy.
This prevents the operator from seeing this error as "CHEFINT001" and a message dump of the original train error, instead presenting instructions on how to resolve the error.
> Provide instructions via error message when no auth method is available.

- .github/PULL_REQUEST_TEMPLATE.md
- Docs are an important part of providing a first-class UX, so I added
them to the PR template.
- Removed DCO from checklist, because the DCO bot will block the PR from merge
until commits are all signed off
- Added a sanity check for verifying submitter has run the code locally
from end-to-end, and not just run the tests.
n/a
n/a
> Add docs to the PR template checklist

- omnibus/resources/chef-workstation/msi/source.wxs.erb
> Capitalization issue in Windows package (wix)

- omnibus/config/software/chef-workstation-app.rb
- omnibus/resources/chef-workstation/msi/localization-en-us.wxl.erb
- omnibus/resources/chef-workstation/msi/source.wxs.erb
This adds a "Chef Workstation App" feature to the Windows
Installer.  It provides a 'run on login' component that will
add CWA to common startup
If Start menu items are selected, it will include this
shortcut there as well.
This branch also renames the shell shortcut "Chef Workstation" to "Chef
Workstation Command Prompt". This is more in line with recent
discussions around naming, and avoids confusion between a shortcut
called "Chef Workstation" and one named "Chef Workstation App".
This also changes the CWA tray app package location to $install_path/components/chef-workstation-app instead of $install_path/installers - it's more accurate.
> [SHACK-353] Enable CWA on Windows

- omnibus/config/software/chef-workstation-app.rb
- omnibus/package-scripts/chef-workstation/postinst
This PR updates the chef-workstation-app build to whitelist node-related binaries,  and keep directory mode without rezipping the CWA deployment. 
In postinst, it adds a simple check to see if CWA is runnable by verifying required libs are present. If it is, it will link it into $install/bin. Otherwise, it prints an informational message letting the operator know that chef-workstation-app will not be available.
Pending merge of #241
> [SHACK-348] Enable CWA on linux

- .expeditor/config.yml
- .expeditor/update_chefdk_to_stable.sh
- omnibus/config/projects/chef-workstation.rb
Expeditor will manage the pinned version for us. Whenever ChefDK is released it will update the omnibus pin.
SHACK-357
> [SHACK-357] Include latest stable release of ChefDK

- .expeditor/config.yml
- .expeditor/update_chef-workstation-app_to_latest.sh
- omnibus/config/projects/chef-workstation.rb
This change attempts to subscribe to merge events
on chef/chef-workstation-app and use that to manage
our dependency on the project.
> Subscribe to Workstation App pr merges

- omnibus/config/projects/chef-workstation.rb
This pull request was triggered automatically via Expeditor when Chef Workstation App 0.0.30 was merged.
This change falls under the obvious fix policy so no Developer Certificate of Origin (DCO) sign-off is required.
> Bump Chef Workstation App to 0.0.30

- omnibus/config/projects/chef-workstation.rb
- omnibus/config/software/uninstall-scripts.rb
- omnibus/files/uninstall-scripts/uninstall.sh
- omnibus/package-scripts/chef-workstation/postinst
This change adds an uninstall program for macs to /usr/local/bin.
> Mac uninstall program

- omnibus/files/uninstall-scripts/uninstall.sh
1. Prompt user for password before closing app message during uninstall.
2. Only show closing app message if app is running.
During uninstall the the user interaction was like:
```
This uninstaller will remove Chef Workstation
Enter your password to continue
Closing Chef Workstation App
Password:
Uninstalling Chef Workstation
Removing files
Removing binary links in /usr/local/bin
Forgeting com.getchef.pkg.chef-workstation package
Forgot package 'com.getchef.pkg.chef-workstation' on '/'.
Chef Workstation Uninstalled
```
This change fixes it to:
```
This uninstaller will remove Chef Workstation.
Password:
Closing Chef Workstation App...
Uninstalling Chef Workstation...
-> Removing files...
-> Removing binary links in /usr/local/bin...
-> Forgeting com.getchef.pkg.chef-workstation package... …
```
> Clean up user messaging order in uninstall script

- omnibus/package-scripts/chef-workstation/postinst
This corrects a reversed `postinst` conditional that would cause the package install to tell the user that they could run chef-workstation-app when there were still deps to install.
> Fix reversed condition for CWA lib detection

- omnibus/package-scripts/chef-workstation/postinst
We need to close the tray app and remove it before
the new version can be installed. If the app was running
we restart the app.
> Fixes tray app upgrades on mac

- www/site/content/docs/chef-workstation/chef-run-users-guide.md
Also doing general cleanup.
N/A
> Removing some copyrighted names from examples

- www/site/content/docs/chef-workstation/chef-run-users-guide.md
> Fixing a bad link in documentation

- omnibus/Gemfile.lock
- omnibus/config/projects/chef-workstation.rb
chef-cleanup has been renamed to ruby-cleanup since that's what it
actually is. This updates the omnibus definition to use the new
definition name.
> Update omnibus to use ruby-cleanup

- omnibus/config/projects/chef-workstation.rb
- www/site/content/docs/chef-workstation/install.md
An unintended side effect of declaring that chef-workstation
replaces chefdk is that our yum/apt repositories will identify
chef-workstation as replacing chefdk - so anyone with chefdk installed
who runs yum/apt upgrade will receive chef-workstation instead of the
updated chefdk.
#297
> Do not 'replace' chefdk in linux packaging for now

- .expeditor/update_chef-workstation-app_to_latest.sh
- omnibus/config/projects/chef-workstation.rb
- omnibus/config/software/chef-workstation-app.rb
Move the pin and update of chef-workstation-app version
to occur within the chef-workstation-app.rb software definition
instead of a project-level override.
This prevents invalidating the build cache when chef-workstation-app revs.
> Pin chef-workstation-app version in its software definition

- .gitmodules
- www/.gitignore
- www/Makefile
Git submodules can be fragile, we'll move to the pattern we use for
automate-www/a2 now:
https://github.com/chef/a2/pull/2679
> Switch from using git submodules to ignored folders for www dependencies

- omnibus/config/patches/chef-dk/cli.patch
- omnibus/config/software/chef-dk.rb
This change monkey patches cli.rb from chefdk durning the omnibus build so that it shows chef workstation's version.
```
➜  omnibus git:(jm/patch_chef_cli) ✗ chef -v
Chef Workstation Version: 0.2.25+20181020052834
chef-dk version: 3.4.18
chef-apply version: 14.5.33
chef-client version: 14.5.33
delivery version: master (6862f27aba89109a9630f0b6c6798efec56b4efe)
berks version: 7.0.6
kitchen version: 1.23.2
inspec version: 2.2.112
```
> Display workstation version in `chef -v`

- .expeditor/announce-release.sh
- .expeditor/config.yml
- .expeditor/publish-release-notes.sh
- .expeditor/purge-cdn.sh
This change introduces the release notes process we have been
solidifying for Automate 2:
- Release Notes are captured in a simple wiki page on the project repository: https://github.com/chef/chef-workstation/wiki/Stable-Release-Notes
- These captured release notes are then automatically published to a known publicly accessible location when the promotion to `stable` is executed
Please remember release notes are not changelogs! The audience is our end-users, not other engineers. If you need a quick primer on what goes into good release notes, take a look at these excellent articles:
https://medium.com/@DigitalGov/the-life-changing-magic-of-writing-release-notes-4c460970565
https://www.prodpad.com/blog/writing-release-notes/
The published release notes are available at the following URLs: …
> Introduce Release Notes process; Announce releases on discourse.chef.io

- omnibus/Gemfile.lock
- omnibus/config/projects/chef-workstation.rb
This disables appx packages and updates omnibus to latest. 
* Update omnibus to the latest to get the new packager
attribute 'skip_packager'. 
* Turn off windows appx packages via `skip_packager` to speed up Jenkins builds.
> disable appx packages; update to latest omnibus

- .expeditor/announce-release.sh
- .expeditor/publish-release-notes.sh
- .expeditor/purge-cdn.sh
- .expeditor/update_chef-workstation-app_to_latest.sh
- .expeditor/update_chefdk_to_stable.sh
- .expeditor/update_delivery-cli_to_latest.sh
Expeditor now adds the `EXPEDITOR_` prefix to environment variables it
manages so it is easier to determine where environment variables
come from.
Signed-off-by: Tom Duffield <tom@chef.io>
> Add EXPEDITOR_ prefix to environment variables

- omnibus/Gemfile.lock
- omnibus_overrides.rb
We're not shipping the same stuff that we ship in DK and we're actually
shipping insecure versions of many of these libraries. This gets us up
to the same level that DK 3 is at.
> Bump bundler/rubygems/openssl

- omnibus/package-scripts/chef-workstation/postinst
- omnibus/package-scripts/chef-workstation/postrm
This change removes the `chefx` binary references in `postinst` and `postrm` as it is a relic of old versions and is no longer used.
Requesting a pull to chef:master from chef:jtimberman/nix-chefx
Write a message for this pull request. The first block
of text is the title and the rest is the description.
> remove chefx symlink references

- omnibus/omnibus-test.ps1
This is a minor change to the new `omnibus-test.ps1` script so it downloads the package for the correct architecture.
> Minor changes to omnibus-test.ps1 script

- omnibus/Gemfile.lock
- omnibus/config/patches/chef-dk/base.patch
- omnibus/config/patches/chef-dk/cli.patch
- omnibus/config/software/chef-dk.rb
- omnibus/omnibus-test.ps1
- omnibus/omnibus-test.sh
- omnibus_overrides.rb
This bumps ChefDK to 4.0.67, which is greater than the latest stable
release (4.0.60). We need to do that in order to get a chef-apply that
works with ChefDK 4.0
Differences between .60 and .67 are at
https://github.com/chef/chef-dk/blob/cedb19fd8d05cc1070134a5b920d2560399d7f7d/CHANGELOG.md#changes-since-4060-release
It includes some CVE fixes and docs fixes in addition to the chef-apply
gem bump.
N/A
> Preparing for Chef Workstation 0.4 release - EULA support

- .expeditor/release.omnibus.yml
It's EOL and we shouldn't be building on it anymore
> Stop building on Ubuntu 14.04

- omnibus/omnibus-test.ps1
- omnibus/omnibus-test.sh
This just updates the `omnibus-test.*` scripts to use tools that have been moved into the omnibus-toolchain. It also makes some changes to output to be more consistent across our omnibus projects.
> Use new omnibus-toolchain scripts in omnibus-test.* scripts

- omnibus/config/patches/chef-dk/cli.patch
- omnibus/config/software/chef-dk.rb
This all goes away when we switch to the Chef CLI. Then we'll need to find another way to do it all.
> Fix the chef --version command showing the old DK version

- .expeditor/config.yml
- omnibus_overrides.rb
We already made this same change in DK
> Pin Rubygems to 3.0.3 to prevent double bundler

- omnibus_overrides.rb
rubygems ships its own bundler which may differ from bundler
already defined and then we get double bundler which results in
performance issues / CLI warnings. Make sure these versions
match before bumping either.
> downgrade rubygems to 3.0.3

- omnibus/Gemfile.lock
Make sure we have the double bundler detection logic in ruby-cleanup.
> Update to the latest omnibus-software for double bundler detection

- .expeditor/release.omnibus.yml
This will get us a Windows 2019 build on the downloads page
> Add Windows 2019 build verification

- .expeditor/announce-release.sh
This will ensure the Markdown that is part of the undelrying release
notes is not mixed in with the Markdown in the rest of the Discourse
announcement message.
Fixes chef/release-engineering#765
I've also fixed the affected Discourse message at:
https://discourse.chef.io/t/chef-workstation-0-8-7-released/15745
> Surround announcement release notes with newlines

- omnibus/config/software/windows-env-customization.rb
There is no longer a `windows-env-customization` folder, it got renamed to `env-customization`. We could fix this by 1) specifying the path instead of using the software definition name or 2) rename the software def to `env-customization` so the name matches the existing path.
N/A
> Fixing a broken path in the omnibus build

- omnibus/Gemfile.lock
This resolves a CVE in git and gives our user base the latest git functionality.
> Update git on windows to 2.23.0

- omnibus/config/software/git-custom-bindir.rb
> Update git for non-Windows platforms to 2.23.0

- .expeditor/verify.pipeline.yml
- Gemfile
- omnibus/omnibus-test.ps1
- omnibus/omnibus-test.sh
- omnibus/verification/README.md
- omnibus/verification/component_test.rb
- omnibus/verification/run.rb
- omnibus/verification/spec/spec_helper.rb
- omnibus/verification/spec/unit/component_test_spec.rb
- omnibus/verification/spec/unit/fixtures/eg_omnibus_dir/valid/embedded/apps/berkshelf/integration_test
- omnibus/verification/spec/unit/fixtures/eg_omnibus_dir/valid/embedded/apps/berkshelf/verify_me
- omnibus/verification/spec/unit/fixtures/eg_omnibus_dir/valid/embedded/apps/chef/verify_me
- omnibus/verification/spec/unit/fixtures/eg_omnibus_dir/valid/embedded/apps/test-kitchen/verify_me
- omnibus/verification/spec/unit/verify_spec.rb
- omnibus/verification/verify.rb
This moves the `verify` command into chef-workstation, since it is only used to verify the builds in the omnibus pipeline. This helps reduce the indirect circular dependency between Workstation and CLI as well, since CLI no longer needs to know about what tools ship with Workstation.
This is minimally modified transplant of the `Verify` class and the supporting class `ComponentTest`. Once all is well, we can update `chef-cli` to remove the `verify` command. 
> Transplant verify functionality from chef-cli

- omnibus/config/projects/chef-workstation.rb
- omnibus/config/software/chef-analyze.rb
- omnibus/omnibus-test.ps1
- omnibus/omnibus-test.sh
- omnibus/package-scripts/chef-workstation/postinst
- omnibus/package-scripts/chef-workstation/postrm
Package the new `chef-analyze` Go binary. (https://github.com/chef/chef-analyze)
GH Issue: https://github.com/chef/chef-workstation/issues/552
Depends on https://github.com/chef/omnibus-software/pull/1098
> Package new `chef-analyze` binary

- Dockerfile
Signed-off-by: Brent Smith <brent.smith@lightspeedhq.com>
Binaries were not executable without specifying their entire path.
```
:➜  ~ docker run --rm -it chef/chefworkstation which bundle
:➜  ~ docker run --rm -it chef/chefworkstation:issue564 which bundle
/opt/chef-workstation/embedded/bin/bundle
```
Fixes https://github.com/chef/chef-workstation/issues/564
- [ x] Bug fix (non-breaking change which fixes an issue)
- [ x] I have read the **CONTRIBUTING** document.
- [x ] I have run the pre-merge tests locally and they pass.
- [x ] All new and existing tests passed.
- [x ] All commits have been signed-off for [the Developer Certificate of Origin](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco).
> Fix typo in PATH /opt/chefworkstation -> /opt/chef-workstation

- components/gems/Gemfile
- components/gems/Gemfile.lock
This way we don't ship two copies of fauxhai
> Depend on ChefSpec 9 and swap the faxhai dep

- components/gems/Gemfile
- components/gems/Gemfile.lock
This syncs this gemfile with changes we've made in DK
> Update Chef to 15.4 and remove explicit rubocop from the Gemfile

- components/gems/Gemfile
- components/gems/Gemfile.lock
Somehow I still messed up the rebase on https://github.com/chef/chef-workstation/pull/440 so just opening a new PR to get the commits from that merged. Please refer to that PR for all conversation history on this issue.
This closes https://github.com/chef/chef-workstation/issues/541
Currently we can lint ruby (with `rubocop`) but not the `README.md`s.
This includes `mdl` in the omnibus build. It's a lightweight extensible
markdown linter.
Signed-off-by: Phil Dibowitz <phil@ipom.com>
https://github.com/chef/chef-dk/issues/1601
> Include `mdl` markdown linter.

- omnibus/config/software/chef-workstation-app.rb
Adding `--unsafe-perm=true --allow-root` to `npm install`.
This gets around permission errors when building locally
on OSX Catalina.
> Fix Workstation App Build

- .expeditor/update_dockerfile.sh
- README.md
- omnibus/config/projects/chef-workstation.rb
- omnibus/config/software/gems.rb
- omnibus/files/openssl-customization/windows/ssl_env_hack.rb
- omnibus/kitchen.yml
- omnibus/package-scripts/chef-workstation/postrm
- omnibus/resources/chef-workstation/pkg/welcome.html.erb
This updates the readme and installer list of components that we ship to
match what we display in the chef -v output + a mention of knife/kitchen
plugins. This gives users a better idea of what we're shipping in this
package. I also removed all the remaining mentions to DK I could find in
the codebase.
Closes #473 and #472
> Update Mac installer text to list the current components of Workstation

- components/gems/Gemfile
- components/gems/Gemfile.lock
Pin minitest and 5.11.3 which is the version now being brought in and
avoid the rdoc pin entirely since that seems to be causing a double
verion.
> Avoid shipping double rdoc / minitest gems

- components/main-chef-wrapper/main.go
Currently, any `chef` command that requires STDIN interaction is broken,
things like `chef generate cookbook` will ask for accepting the license
and we are unable to do so. Another example is `chef exec irb`.
This PR fixes that problem by linking the STDIN from the terminal to the
underlying spawned command.
```
➜  chef exec irb
Switch to inspect mode.
➜  
```
```
➜  chef exec irb
irb(main):001:0> puts "hello"
hello
=> nil
irb(main):002:0>
``` 
Closes https://github.com/chef/chef-workstation/issues/637
https://github.com/chef/chef-workstation/issues/637
https://github.com/chef/chef-workstation/issues/652
> [bug-fix] Enable interactive 'chef' commands

- omnibus/omnibus-test.ps1
- omnibus/omnibus-test.sh
These echos get a carrot for folding. Without this the stuff gets grouped in with the chef-analyze tests.
> Make it clear in testing when we run the verify suite

- omnibus/config/projects/chef-workstation.rb
- omnibus/config/software/more-ruby-cleanup.rb
See what we can do about our overall file size and count by removing
non-library files from the package.
512MB - > 493MB. 3095 files removed
> Aggressively prune files from the gems we install

- omnibus/config/software/more-ruby-cleanup.rb
This slims the install by 241k on disk and 28 files.
> Cleanup additional files / folders in the installed gems

- .expeditor/announce-release.sh
- omnibus/resources/chef-workstation/msi/localization-en-us.wxl.erb
- omnibus/resources/chef-workstation/msi/source.wxs.erb
We want to get this in the hands of users. This still doesn't install it by default and I removed the desktop shortcut that doesn't make sense.
> Windows install: Remove experimental wording and make workstation top level in the installer

- omnibus/cookbooks/chef-workstation-builder/metadata.rb
- omnibus/cookbooks/chef-workstation-builder/recipes/default.rb
Remove the pin on the very old yum-epel
Simplify the platform logic a bit since apt_update will auto skip on non-debian platforms
> Minor updates to the omnibus cookbook

- omnibus/config/software/more-ruby-cleanup.rb
- Remove /ext dirs from gems since we've already compiled the extensions and no longer need the hundreds of files here
- Remove Rakefile/Gemspec/Gemfile when we don't also have a bin dir (appbundler needs these)
- Remove specs that we're not using in our verify command
This might seem overly complex, but the win is pretty substantial so I'd argue it's worth the trouble. Stats for this PR on my mac:
9.28% reduction in size of /opt/chef-workstation (47.9 megs)
11.47% reductions in /opt/chef-workstation file count (4,934 files)
> Aggressively clean up files in the workstation install

- omnibus/resources/chef-workstation/msi/localization-en-us.wxl.erb
- omnibus/resources/chef-workstation/msi/source.wxs.erb
1) We were never enabling Chef Workstation App. We were installing it. This updated wording is consistent with the actual Chef Workstation wording
2) Rename some components so it's more clear to folks in the future what they do
3) Call it the Chef Workstation Taskbar App in the description so it's more clear what you're selecting
4) Enable the WS App subfeature to enable it at boot. Have this be disabled by default, but this lets us at least test this functionality for when (soon) we make it default
> More improvements to the Windows installer

- omnibus/Berksfile
- omnibus/Gemfile
- omnibus/Gemfile.lock
- omnibus/config/software/more-ruby-cleanup.rb
- omnibus/kitchen.yml
Remove the files that we cleanup already via omnibus-software's
ruby-cleanup definition. There's no reason to cleanup the same files in
both.
> Simplify our Ruby cleanup in ommnibus

- omnibus/config/software/more-ruby-cleanup.rb
There's no need to ship the rake tasks when we've already removed the Rakefile for these gems. This removes 56 additional files which take up 200k on disk.
```
Deleting /opt/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/strings-ansi-0.2.0/tasks/coverage.rake
Deleting /opt/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/strings-ansi-0.2.0/tasks/console.rake
Deleting /opt/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/strings-ansi-0.2.0/tasks/spec.rake
Deleting /opt/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/tty-cursor-0.7.0/tasks/coverage.rake
Deleting /opt/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/tty-cursor-0.7.0/tasks/console.rake
Deleting /opt/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/tty-cursor-0.7.0/tasks/spec.rake
Deleting …
```
> Cleanup rake tasks in gems we ship

- omnibus/Gemfile
- omnibus/Gemfile.lock
- omnibus/config/patches/rb-fsevent-gem.patch
- omnibus/config/projects/chef-workstation.rb
- omnibus/config/software/gems.rb
- omnibus/config/software/git-custom-bindir.rb
- omnibus/config/software/rb-fsevent-gem.rb
This changes makes the neccessary changes to enable the pkg to pass apples notarization requirements.
1. Update omnibus and omnibus-software to versions that support deep signing
2. Drop 'Developer ID Installer:' from signing key. This lets sigining pick up the correct key for what is being signed.
3. Add bin_dirs and lib_dirs to gems and git-custom-bindir software definitions so siging can find their binaries and libraries.
4. Add software definition for rb-fsevent-gem so we build the gem. This resolves an issue where the shipped binary is build on to old an sdk.
5. Patch rb-fsevent-gem build to work in our environment. Set minimum target to current os and discover the sdk version.
* Note it is currently pointed at branches in omnibus and omnibus software. Let's work towards merging this …
> Fixes all notarization issues

- .expeditor/release.omnibus.yml
It's a valid desktop platform and there's no additional work above already supporting Ubuntu. This gives us feature parity with DK which includes this same config.
> Produce Debian packages

- habitat/plan.sh
- omnibus/config/software/gems.rb
Due to pins in inspec vs. inspec-core in 4.18.51 we're getting failures.
This will be resolved with a new inspec release, but that doesn't
unblock us today.
> Exclude omnibus_packages in chef bundle testing

- omnibus/Gemfile.lock
- omnibus/resources/chef-workstation/pkg/entitlements.plist
ffi loads c code into memory in an unsigned way and this allows workstation
to work with the hardened runtime.
> Adding entitlement for unsigned memory execution

- omnibus/files/uninstall-scripts/uninstall_chef_workstation
- omnibus/package-scripts/chef-workstation/postinst
This change has a dependency on chef/chef-workstation-app#153 and once it is
merged it will enable the Chef Workstation App to be run at boot by leveraging
the new `chef_workstation_app_launcher` script.
https://github.com/chef/chef-workstation/issues/819
> mac_os:(launcher) run at boot

- www/site/content/docs/chef-workstation/chef-run-users-guide.md
Signed-off-by: Nick Rycar <nickrycar@Nicks-MacBook-Pro.local>
One of the token links in the Automate 2 section of the docs returns a 404. Updating to match the working link later in the doc. 
Minor typo fix. No issue logged.
Docs only change. Didn't touch tests.
> Fix link to api tokens in user guide

- components/gems/Gemfile.lock
Both of these reduce the number of files that need to be loaded and speed up knife operations for all plugins.
> Update knife-ec2 to 1.0.31 and knife-vsphere to 4.1.3

- omnibus/package-scripts/chef-workstation/postinst
Update the `postinst` to run the Workstation App as a mortal user instead of `root`.
Depends on https://github.com/chef/chef-workstation-app/pull/160
> postinst:(su) run the Workstation App as mortal user

- .expeditor/release.omnibus.yml
We have verifiers for Debian 10 now
> Validate builds on Debian 10

- components/gems/Gemfile.lock
This adds functionality necessary for kitchen-pester, makes accepting the license simpler in CI environments, and passes all system env vars into the guest so they can be examined.
> Update Test Kitchen to 2.4.0

- components/gems/Rakefile
A continuation of
https://github.com/chef/chef-workstation/commit/e7f09766a64a4e065d885acc509112a7a65f8fe8
to try to fix our builds.
> Pinning bundler to 1.17 because 2.x breaks our builds

- components/gems/Gemfile.lock
I fixed the `update_deps.sh` script so this should not happen anymore, then merged a 6 day old PR that had been made before that script was fixed 🙄
> I accidently bumped the bundler version after fixing the update dep script

- docs/Where-Do-Cookbooks-Come-From.md
This documents when/where cookbooks and dependencies are
specified and resolved, and how the client ingests this data. 
Fixes #889 
> Document runlist expansion/determination and cookbook sourcing

- www/Makefile
- www/README.md
- www/content/workstation/_index.md
- www/content/workstation/chef-workstation-app.md
- www/content/workstation/config.md
- www/content/workstation/ctl_kitchen.md
- www/content/workstation/privacy.md
- www/content/workstation/troubleshooting.md
- www/layouts/shortcodes/ws_knife_ssl_check_bad_ssl_certificate.md
- www/themes/docs-new/layouts/shortcodes/readFile_shortcode.html
- www/themes/docs-new/layouts/shortcodes/shortcode_indent.html
This corrects a few minor-ish issues with docs in the `www` directory.
- corrects the hugo server command in the Makefile
- consolidates two nearly identical shortcodes into one
- removes a duplicate toml config from a page
- adds `edit on GitHub` links to several pages
- update the readme file
> Updates documentation in chef-workstation

- .expeditor/announce-release.sh
The Discourse API has recently changed it's authentication method and the underlying issue was fixed in Expeditor's `post_discourse_release_announcement` helper function: https://github.com/chef/expeditor/pull/1240
> Use Expeditor's built in Bash helper to post release announcement

- .expeditor/config.yml
- .expeditor/third-party-packages.pipeline.yml
This creates the pipeline that will be used to publish packages to chocolately. 
> Add empty third party pkg pipeline to expeditor

- .expeditor/config.yml
- .expeditor/publish_to_chocolatey.ps1
- .expeditor/third-party-packages.pipeline.yml
- components/packaging/chocolatey/chef-workstation.nuspec
- components/packaging/chocolatey/tools/chocolateyinstall.ps1
This adds Chocolatey to the third-party-packages
buildkite pipeline, so that every stable release will
get published to Chocolatey.
> Enable auto-publishing stable releases to choco 

- components/gems/Gemfile
- components/gems/Gemfile.lock
- omnibus/config/software/docker-api.rb
- omnibus/config/software/gems.rb
The ruby cleanup omnibus software dep removes the gem installed by
bundler. I am not sure how Ohai does not have this issue. Reverting
to a pattern I understand to fix our build for now.
In the future it would be nice to only have to manage this gem via
the Gemfile and without the docker-api omnibus software definition.
https://buildkite.com/chef/chef-chef-workstation-master-omnibus-release/builds/356#eb929cfb-d3cb-4862-9990-75c1a99c09d0
> Manually building and installing docker-api gem

- .expeditor/update_dep.sh
- omnibus/config/software/git-custom-bindir.rb
Our dep bumping jobs appear to be getting killed, and I am still troubleshooting that. But there is no reason to install documentation for these gems when our goal is to update the `Gemfile.lock`.
> Speed up dep bumping jobs by not installing gem documentation

- omnibus/config/software/ruby-windows-system-libraries.rb
This PR is in preparation for introducing MSYS_INSTALL_DIR environment variable in next release of omnibus-toolchain. We do not ship msys2 for windows in omnibus-toolchain anymore, so this variable sets the PATH where msys2 is installed on the AMI
Signed-off-by: Jaymala Sinha <jsinha@chef.io>
Set msys2_path to the path defined by MSYS_INSTALL_DIR for Windows builds
> Update Windows msys2_path to custom installed msys2 lookup first

- www/netlify.toml
Netlify shouldn't make build previews for changes made outside of the `www` directory.
This should fix the git diff command so it will ignore changes outside of `www`.
> Fix netlify build ignore

- omnibus/verification/spec/unit/verify_spec.rb
- omnibus/verification/verify.rb
chef-utils (from chef/chef/chef-utils) is included as part of core chef
now and includes most of the helpers that used to be separately shipped
in the chef-sugar library. We no longer ship the chef-sugar library and
thus no longer need to test it.
> chef-sugar helpers are now in chef-utils

- www/content/workstation/config_yml_kitchen.md
- www/layouts/shortcodes/ws_test_kitchen_drivers.md
Make sure we don't mention kitchen-docker anymore, add dokken and azure
and make sure we note which ones are in Workstation.
> Update the list of Kitchen Drivers

- .expeditor/run_linux_tests.sh
- .expeditor/verify.pipeline.yml
- Gemfile
- omnibus/verification/verify.rb
This is the same pattern we're using in all our other projects.
> Cache gems in testing using Expeditor gem caching

- .expeditor/config.yml
There's no need to waste CPU cycles if these are released again
> Remove expeditor subscriptions for chef-sugar and foodcritic

- .expeditor/config.yml
- omnibus/verification/verify.rb
Prevents things like https://github.com/chef/chef-workstation/pull/1174
that try to merge cw-18 to master.
> unsubscribe to dep updates to prevent dual PRs

- components/main-chef-wrapper/dist/global.go
- components/main-chef-wrapper/main.go
- omnibus_overrides.rb
This makes the top-level command used for analyze features
of 'report' and 'capture' route under the command 'report':
These are now valid:
chef report nodes (chef-analyze report nodes)
chef report cookbooks (chef-analyze report cookbooks)
chef report upload  (chef-analyze upload)
chef report session (chef-analyze session)
chef capture (chef-analyze capture)
Note that there are corresponding branches of the
same name in chef-analyze and go-libs. These will need to merge
before this branch.
> 'analyze' is now 'report'

- components/main-chef-wrapper/main.go
These should all go the same path as the no-argument
route, displaying local help through usage() and exiting 0.
> Ensure help, -h, and --help behave the same

- .expeditor/config.yml
- .expeditor/push-git-tag.sh
Normally expeditor does a 'git tag' for us when we use
'built_in:bump_version' but in this case we are doing the version bump
on our own since sometimes we do a major/minor bump based on the the
date.
> Push a git tag after a VERSION change

- components/main-chef-wrapper/main.go
- omnibus_overrides.rb
- www/content/workstation/config.md
Remove the "Experimental" section from the usage output of the main CLI wrapper, merging its contents with the rest of the usage.
Makes `report` and `capture` commands available without the feature flag.
Also updates the config docs to remove mention of the `analyze` setting, while leaving docs in place for the feature flags mechanism in general.
Partially implements #1135
> Remove Upgrade Lab feature flag from usage and config docs

- components/gems/Gemfile
- components/gems/Gemfile.lock
- omnibus_overrides.rb
This bumps the RuboCop engine from 0.83 -> 0.85 with a large number of
autocorrection bug fixes and it also includes a critical new cop for
detecting a major breaking change in Chef 16.
> Update cookstyle to 6.7

- components/gems/Gemfile
- components/gems/Gemfile.lock
- omnibus/Gemfile
- omnibus/Gemfile.lock
> Working around a build time segfault with FFI 1.13

- components/gems/Gemfile
- components/gems/Gemfile.lock
Nukes a large pile of deps and slims down the app a bit.
backports 671 files / 2.5MB on disk
gherkin: 23 files / 209k on disk
cucumber-core: 55 files / 221k on disk
cucumber-tag-expressions: 10 files / 25k on disk
~3 megs shaved off the install and 759 files
> Update Foodcritic to 16.3 to remove gherkin/cucumber/backports

- components/gems/Gemfile
- components/gems/Gemfile.lock
- omnibus/Gemfile.lock
- omnibus/config/software/gems.rb
Pin minitest to 5.13 to avoid the warnings that 5.13 and 5.14.1 has been activated. Due to how we handle gems we need to make sure we avoid this.
> Upgrade groups in appbundling and avoid double minitest

- .expeditor/config.yml
- .expeditor/update_habitat.sh
- omnibus/config/projects/chef-workstation.rb
- omnibus/config/software/habitat.rb
- omnibus/omnibus-test.ps1
- omnibus/omnibus-test.sh
- omnibus/package-scripts/chef-workstation/postinst
- omnibus/package-scripts/chef-workstation/postrm
- omnibus/verification/verify.rb
We want to ensure that Workstation includes all of the tools required to
manage infrastructure - Chef Habitat is a key part of that.
- This adds a software definition to include the pre-built
Chef Habitat 'hab' binary for each supported platform at WS build-time,
in the same way we bundle workstation-app. We can visit switching this
to build the binary instead of downloading pre-built in future
iterations.
- It adds an update script to update the definition to the latest stable
version of habitat.
- it adds an expeditor workload to trigger that script when a stable hab
is published.
- it adds a post-inst step that checks for conflicting `hab` install and
warns the operator thta WS should now manage the install.
> Add the habitat binary to the Workstation package

- .expeditor/config.yml
- .expeditor/purge-cdn.sh
This new action was added since we last promoted and we are required
to use the built-in rather than a bash script now.
> Use built-in action for CDN purge

- .expeditor/update_habitat.sh
- omnibus/config/software/habitat.rb
This will ensure that the omnibus build manifest reflects the
correct version number instead of 'latest'.
> Update default_version of habitat during build

- omnibus/files/uninstall-scripts/uninstall_chef_workstation
- omnibus/omnibus-test.sh
- omnibus/package-scripts/chef-workstation/postinst
- omnibus/package-scripts/chef-workstation/postrm
- omnibus/package-scripts/chef-workstation/preinst
uname -a is far more reliable here for detecting Darwin.
> Make sure macOS detection works even if the string changes

- omnibus/Gemfile.lock
- omnibus/config/software/more-ruby-cleanup.rb
Some of this is work from omnibus-software itself and some of it is part of the omnibus config specific to workstation:
1) Update cacerts to the latest release. This revokes some certs
2) Update curl from 7.68.0 to 7.71.1 which includes a large number of bug fixes. We've also updated our curl omnibus config to remove support for gopher, imap, imaps, pop3, pop3s, smtp, and smtps protocols, which makes the binary a bit smaller (~40k).
3) the bzcat binary is no longer being built with libarchive which drops install size by ~250k
4) The unused chef functional/integration/stress specs are removed from the install in the cleanup definition.  This is 242 files / 1.9 megs on disk
Overall this removes 243 files and 2.2 megs on disk.
> Reduce the size of the Chef Workstation package / install

- omnibus/Gemfile.lock
We're shipping several dozen empty gem dirs in the install that have to
be installed every time. This PR cleans that all up.
> Update omnibus-software to cleanup empty gem dirs

- .expeditor/create_pr_for_homebrew.sh
- .expeditor/third-party-packages.pipeline.yml
* switch to the macos executor, because the non-ES linuxbrew image is
not a permitted to access expeditor secrets.
* Updates buildkite emoji alias to be :mac:
* mac-compatibility fixes for sed usage.
* Fix PR request to set maintainer_can_modify to false. This otherwise
fails the PR with a message about the non-existent field
`fork_collab`, possibly because the account creating the branch
(chef-ci) doesn't have proper push access to the branch, triggering
an odd validation failure from GH API.  Ref: https://github.com/octokit/rest.js/issues/490
* fix indentation issue in third party package pipeline yml (tball,
squashed)
> Fix Homebrew PR creation

- www/content/workstation/config_rb.md
- www/content/workstation/config_rb_optional_settings.md
- www/content/workstation/knife_status.md
Hide healthy has been deprecated for many many years and is gone with
Chef Infra Client 15.
> Replace docs for hide-healthy with hide-by-mins

- www/content/workstation/install_workstation.md
Add instructions to install Workstation without enabling Workstation App to a headless/unattended Windows environment. 
> Add headless/ws-appless windows install instructions

- .studiorc
Signed-off-by: Mudassar Shafique <15931574+mudash@users.noreply.github.com>
This is not a supported arch for any OS. And with golang 15.1 it's  
giving us build errors on darwin/386, which is now unsupported.
> Removing 386 arc to support go 1.15 with hab build

- omnibus/omnibus-test.ps1
- omnibus/omnibus-test.sh
- www/Makefile
Also cleaning up how we update our `chef-web-docs` submodule to ensure it doesn't get downgraded again
> After removing the /usr/local symlink we need to chef exec our test so it finds the utility in embedded/bin

- components/gems/Gemfile.lock
> Update kitchen-vagrant to 1.7.1

- components/gems/Gemfile
- components/gems/Gemfile.lock
This is bundled with chef itself for super low level debugging of the client that I suspect next to no one has ever done. You shouldn't even be running that on the workstation install so this is just a waste of 5 megs on Windows.
> Remove ruby-prof gem

- docs-chef-io/content/workstation/install_workstation.md
- Add Habitat as a component
- Don't link to chef.sh anymore
- Link to the correct downloads page
- Update examples with the latest package
> Update the install Chef Workstation page

- omnibus/config/software/rb-fsevent-gem.rb
Newer versions of xcode on MacOS 10.15 returns a full semver so see if we have a full semver and account for that.
Signed-off-by: Lance Albertson <lance@osuosl.org>
> Ensure we set only major/minor version for MACOSX_DEPLOYMENT_TARGET

- components/gems/Gemfile
- components/gems/Gemfile.lock
- omnibus_overrides.rb
> Bump Chef to 16.8.9 and chef-workstation-app to 0.1.103

- docs-chef-io/content/workstation/config_rb.md
> Remove the old syntax_check_cache_path config

- docs-chef-io/content/workstation/config_rb.md
Rely on softwrap and nuke some old infra client release notes
> Minor cleanup of the config.rb page

- .expeditor/config.yml
- components/gems/Gemfile
- components/gems/Gemfile.lock
- docs-chef-io/content/workstation/ctl_chef.md
- docs-chef-io/content/workstation/knife.md
- habitat/plan.sh
- omnibus/config/software/gems.rb
- omnibus/package-scripts/chef-workstation/postinst
- omnibus/package-scripts/chef-workstation/postrm
- omnibus/verification/spec/unit/verify_spec.rb
- omnibus/verification/verify.rb
Remove the push jobs client and knife-push since Push Jobs is EOL as of 12/31/2020.
> Remove the EOL Push Jobs Client

- omnibus/config/software/gems.rb
> Don't define libarchive twice in the omnibus config

- .expeditor/config.yml
Remove the alias that is the same name as the project
Add another build skip when in a documentation PR
Use a better header in the changelog for unreleased changes
> More updates to our expeditor config

- omnibus_overrides.rb
Signed-off-by: Nikhil Gupta <nikhilgupta2102@gmail.com>
Added the sha for libarchive version 3.5.1 and make it to the default version in omnibus-software repo and pulling here the updates
[https://github.com/chef/chef-workstation/blob/master/omnibus_overrides.rb#L12](url)
Updated the libarchive version to 3.5.1
[https://github.com/chef/chef-workstation/issues/1618](url)
> libarchive version updated to 3.5.1

- docs-chef-io/content/workstation/knife_client.md
Per the help message from knife itself, this is not an option any longer.
```bash
♠ chef --version
Chef Workstation version: 21.1.222
Chef Infra Client version: 16.9.16
♠ knife client create --help
knife client create CLIENTNAME (options)
-s, --server-url URL             Chef Infra Server URL.
--chef-zero-host HOST        Host to start Chef Infra Zero on.
--chef-zero-port PORT        Port (or port range) to start Chef Infra Zero on. Port ranges like 1000,1010 or 8889-9999 will try all given ports until one works.
--key KEY                    Chef Infra Server API client key.
--[no-]color                 Use colored output, defaults to enabled.
-c, --config CONFIG              The configuration file to use.
--config-option OPTION=VALUE Override a single configuration option.
--defaults …
```
> docs: Remove --admin from knife client create docs

- docs-chef-io/content/workstation/config_rb_optional_settings.md
- docs-chef-io/content/workstation/knife_client.md
- docs-chef-io/content/workstation/knife_user.md
The `--admin` option was removed for `user create` but wasn't removed from the docs. The current draft may go too far and still needs compared to the code.
> Removes admin flag

- components/gems/Gemfile
- components/gems/Gemfile.lock
> Update kitchen-vagrant to 1.8.0

- omnibus/config/software/nodejs-binary.rb
NodeJS 11 is not an LTS release and is EOL
> Update nodejs to 14.15.4

- docs-chef-io/content/workstation/ctl_chef.md
The docs that describe configuration for `chef export` are incorrect. All of the config settings described are either irrelevant or refer to obsolete settings that are dangerous to use. In particular setting `policy_document_native_api` to `false` as the docs say will break everything.
Most of the problematic text is in chef-web-docs, which is fixed here: https://github.com/chef/chef-web-docs/pull/2927
> Remove (wrong) config docs for `chef export`

- docs-chef-io/content/workstation/foodcritic.md
Keep it around for links / search, but nuke it from the menu
> Don't include Foodcritic docs in the menu

- components/gems/Gemfile
- components/gems/Gemfile.lock
This is due to the way the net-ping gemspec is structured at the moment:
It's resolved by https://github.com/eitoball/net-ping/pull/32
> Add a dep on win32-security to resolve failures in kitchen-vcenter

- omnibus/package-scripts/chef-workstation/postinst
Our load script just makes it run at boot. It doesn't actually start the app up. Use AppleScript post install to do that. Also cleanup the whole components dir since that holds nothing but the zip file instead of just removing the zip file and leaving behind a few empty dirs.
> Launch Chef Workstation App post install on macOS

- omnibus/Gemfile.lock
This should speed up some operations
> Compile with -O3 not -O2 optimizations on Linux/macOS

- .expeditor/release.omnibus.yml
We support N-2 for macOS releases
> Remove macOS 10.13 from the build matrix

- docs-chef-io/content/workstation/_index.md
Remove ChefSpec since we're moving away from that
Remove the individual Test Kitchen plugins since they're not tools, but just part of Test Kitchen
Add InSpec. How was that missing.
Also fix some weird formatting around the generator command.
> Update Workstation description with a better list of tools

- docs-chef-io/content/workstation/install_workstation.md
> Add Amazon Linux 2 as a supported OS

- .expeditor/third-party-packages.pipeline.yml
It just throws 404s for a LONG time
> Extend the chocolatey.org push timeout to 60 minutes

- omnibus/config/projects/chef-workstation.rb
Previously we wanted to prevent accidentally upgrading from DK. A this
point we want to make the upgrade easy. Change the conflict to a replace
so that this package can replace the old packages without errors.
Here's the old error:
```
[root@iZrj996x25ht5omuhhzod7Z ~]# rpm -i chef-workstation-21.2.292-1.el7.x86_64.rpm
warning: chef-workstation-21.2.292-1.el7.x86_64.rpm: Header V4 DSA/SHA1 Signature, key ID 83ef826a: NOKEY
error: Failed dependencies:
chefdk conflicts with chef-workstation-21.2.292-1.el7.x86_64
```
> Replace chefdk installs instead of failing

- components/gems/Gemfile
- components/gems/Gemfile.lock
inspec-bin deps on inspec. there's no need to dep on both
> Simplify our inspec dep in the gemfile

- components/gems/Gemfile
- components/gems/Gemfile.lock
There's really no reason to ship yard in Chef Workstation and it's a
pretty big dep
> Remove the yard dependency

- .expeditor/update_dep.sh
Look for env vars from both artifact_published and ruby_gem_published.
Signed-off-by: Tom Duffield <tom@chef.io>
> Support artifact_published workload data

- docs-chef-io/content/workstation/install_workstation.md
> Remove macOS 10.13 from the docs

- docs-chef-io/content/workstation/config_rb.md
- docs-chef-io/content/workstation/knife_exec.md
Signed-off-by: jan shahid shaik <jashaik@progress.com>
chef_server_url should be https://hostname instead of http://hostname/organizations/orgname/
Knife exec uses the chef_server_url from knife.rb.
If changes need to be made to any global end points like user or user keys,
chef_server_url needs to be updated to https://hostname instead of http://hostname/organizations/orgname/
or a flag for --chef_server_url http:// should be included in the command line.
eg: knife exec -E 'api.delete("/users/myuser/keys/user33")' --server-url https://
> config_rb & knife exec updates for user & user keys global endpoints #2240

- .expeditor/config.yml
This should eliminate the failures on each merge to habitat that we're
seeing right now
> Update the habitat promotion subscription again

- docs-chef-io/content/workstation/install_workstation.md
We don't want to list this anymore
> Remove ChefSpec from the workstation description

- docs-chef-io/content/workstation/install_workstation.md
Uses the shortcode from https://github.com/chef/chef-web-docs/pull/3030 consistently. The updated shortcode contains a description of WS and an updated list of its contents. We need to sync the go module from chef-web-docs & then this should work perfectly.
> Use the chef_workstation shortcode consistently

- components/main-chef-wrapper/dist/global.go
- components/main-chef-wrapper/vendor/github.com/chef/go-libs/distgen/glob_dist.json
- omnibus/config/projects/chef-workstation.rb
- omnibus/resources/chef-workstation/msi/source.wxs.erb
- omnibus/resources/chef-workstation/pkg/welcome.html.erb
Chef.sh is no more. Use https://community.chef.io/tools/chef-workstation/
> Update our website URL to be the community site

- components/gems/Gemfile
- components/gems/Gemfile.lock
- habitat/plan.sh
- omnibus/config/software/gems.rb
- omnibus/package-scripts/chef-workstation/postinst
- omnibus/package-scripts/chef-workstation/postrm
This gets us closer to being able to skip the embedded/bin dir
> Appbundle chef-zero, mixlib-install, and fauxhai

- omnibus/omnibus-test.ps1
- omnibus/omnibus-test.sh
Updated tests to support the use of skip-artifactory-platforms within the shim pipeline definition where packages will be downloaded directly from the buildkite artifacts api.
> Update tests to handle local omnibus packages from Buildkite artifacts api

- .expeditor/release.omnibus.yml
- docs-chef-io/content/workstation/config_yml_kitchen.md
- docs-chef-io/content/workstation/install_workstation.md
- omnibus/kitchen.yml
> Require Ubuntu 18.04 or later

- omnibus_overrides.rb
We don't need this anymore. I fixed the builds with a proper vendoring
> Remove the pin on older Go release

- omnibus/omnibus-test.ps1
- omnibus/omnibus-test.sh
This logic has been moved into the Omnibus Buildkite Plugin.
These scripts can now be used outside of the Buildkite pipelines.
Signed-off-by: Tom Duffield <github@tomduffield.com>
> Remove pipeline-specific logic from test scripts

- docs-chef-io/content/workstation/knife_setup.md
Signed-off-by: Collin McNeese <cmcneese@chef.io>
Updates knife_setup docs to remove `node_name` references from credentials file in favor of `client_name`.
#1987
> Remove references to node_name on knife_setup doc for credentials

- omnibus/verification/spec/unit/verify_spec.rb
> Remove curl as a default component in the verify tests

- omnibus/config/software/git-custom-bindir.rb
I pulled down the git source and ran ./configure to build the automake
config. I then looked at what a default macos install was vs. our
omnibus config. freebsd and macOS are almost identical, but we'd never
actually specified those options for macOS. Our macOS build should look
more like the automake generated version.
> Improve how we built git on macOS

- docs-chef-io/content/workstation/chef_vault.md
The cookbook is dead now that we ship the resources / helpers in Chef
Infra Client itself. Also why are we talking about installation in the
Workstation docs. That's just a waste of space.
> Remove the mention of the chef-vault cookbook and gem installation

- docs-chef-io/content/workstation/plugin_knife_opc.md
Signed-off-by: Sean Horn <horn@progress.com>
Use the equivalent, already functioning chef-server-ctl org- and user- subcommands rather than getting mired in permissions setting and issues running commands as non-pivotal users
> Redirect to chef-server-ctl commands

- docs-chef-io/content/workstation/install_workstation.md
We ship a single package and the app isn't optional anymore. This made
no sense in its own section.
> Collapse the requirements down to a single section

- components/gems/Gemfile.lock
The 0.0.7.7 version isn't compatible with ruby-3.0 on windows (which
makes it a bit of a puzzle that this even built and shipped...)
(I also sorta doubt this "works" on windows, but there's nothing we can do about it, and
this causes the gem depsolver to not immediately puke)
> Rollback unf_ext to 0.0.7.6

- docs-chef-io/content/workstation/config_yml_kitchen.md
The was made in the wrong repo previously. While I was in here I fixed
the default location of the install.sh file.
> Make kitchen docs config change in the right place

- .github/CODEOWNERS
Alert docs team for docs-related PRS.
Docs currently gets notifications for changes to any `.md` files, which is probably unhelpful for everyone involved. This PR adds us to changes in the repo README.md and to `docs-chef-io/`
> Reduce @docs-team PR approvals

- omnibus/config/projects/chef-workstation.rb
- omnibus/config/software/chef-dlls.rb
Signed-off-by: John McCrae <john.mccrae@progress.com>
> Make sure PowerShell DLLs used by Infra Client are properly installed

- .expeditor/release.omnibus.yml
- omnibus/Gemfile.lock
This further optimizes these builds and fixes incorrect package names
that included el7 in their filenames
> Build packages specifically on RHEL 8

- .expeditor/publish-release-notes.sh
Fixes error in expeditor promote script run when wiki is present while cloning
> Clear wiki before cloning from Github.

- .expeditor/config.yml
- omnibus/config/software/chef-workstation-app.rb
* Remove deprecated `merge_actions` from `.expeditor/config.yml`
* Update `chef-workstation-app` to 0.2.64
chef/release-engineering#1627
> Fix Expeditor & Build

- CHANGELOG.md
The expeditor based promote script ran with some failures when the release 21.9.613 was marked as stable. This PR updates the changelog as would have been expected from the automated process.
> Update changelog to include stable release 21.9.613

- .expeditor/config.yml
- components/main-chef-wrapper/.studiorc
Updated the cross platform build script to have `go mod vendor` run prior to `gox`
A few environment variables are present in same file in chef-analyze repo. Adding here for consistency.
https://github.com/chef/chef-workstation/issues/2274
> Fix main-chef-wrapper Go cross platform build that is part of verify pipeline

- docs-chef-io/content/workstation/plugin_knife.md
- docs-chef-io/content/workstation/plugin_knife_custom.md
Signed-off-by: Ian Maddaus <Ian.Maddaus@progress.com>
These pages should be in the workstation menu, not the infra menu.
Related PRs: 
- chef/chef-web-docs#3423
- chef/chef-web-docs#3454
> Fix menu in section in workstation pages

- .expeditor/publish-release-notes.sh
Signed-off-by: Ian Maddaus <Ian.Maddaus@progress.com>
The chef-workstation wiki still uses the master branch.
Release notes should publish correctly now.
> switch chef-workstation wiki to master branch in publish-release-notes

- .expeditor/create_pr_for_homebrew.sh
Updated the `git push` command to exclude `origin` parameter as repository URL is already present.
https://github.com/chef/release-engineering/issues/1675
> just keep git repo URL, remove origin argument

- omnibus/config/software/chef-workstation-app.rb
Relative_path is not working for the copying of files from the zip. Changing to use project_dir instead 
Signed-off-by: Michael Maslanka <maslanka@progress.com>
> Fix Chef Workstation App not being properly bundled

- .expeditor/release.omnibus.yml
- docs-chef-io/content/workstation/install_workstation.md
We support N-2 macOS releases which is now 12, 11, and 10.15.
> Stop producing macOS 10.14 packages

- omnibus/config/software/chef-workstation-app.rb
Whitelist node-related binaries in the chef-workstation-app software definition
Fix copy's source path in chef-workstation-app software definition
> Fix chef workstation app software definition

- omnibus/config/software/git-custom-bindir.rb
The `git` compilation would fail due to incorrect header file being looked up in workstation include folder. Specifically while compiling git, the workstation include folder has been excluded and only other compiler flags kept. This isn't likely the ideal fix as that would require a way to give precedence to current folder while looking up header file. 
https://github.com/chef/chef-workstation/issues/2442
useful reference of similar [issue](https://trac.macports.org/ticket/61628)
> Discard workstation directory in compiler flags when building git

- omnibus/config/software/main-chef-wrapper.rb
Signed-off-by: nitin sanghi <er.nitin.sanghi@gmail.com>
chef main wrapper build using native os and arch support 
Currently build happing for using default os and arch we are now supporting mac m1 chip as darwin arm64 build for go build in chef main wrapper
[issue]( https://github.com/chef/chef-workstation/issues/2519)
> Added support for chef main wrapper for m1

- .expeditor/verify.pipeline.yml
- Dockerfile
- components/gems/Gemfile
We're on Ruby 3 now. We should test on Ruby 3
> Test on Ruby 3 + fix ruby path in dockerfile

- docs-chef-io/content/workstation/config_rb.md
This is a terrible thing that no one should do. We even tell them not to do it here.
> Don't document setting ohai properties in config.rb

- Dockerfile
Signed-off-by: Patrick Schaumburg <pschaumburg@tecracer.de>
On behalf of Patrick Schaumburg - ref https://github.com/chef/chef-workstation/pull/2537
> Add GEM_HOME to environment variables to allow external gem installation

- docs-chef-io/content/workstation/ctl_chef.md
The `delivery` CLI is now obsolete. The delivery workflow related `chef generate build-cookbook` command needs to be removed from the documentation.
https://github.com/chef/chef-workstation/issues/2540
https://github.com/chef/chef-web-docs/issues/3704
> Remove obsolete delivery related subcommand

- .expeditor/config.yml
- .expeditor/update_docs_lints.sh
We need to single-source the documentation lint configurations.
Adds an expeditor config and a script to get the remote files.
> Use Expeditor to get docs lint configs

- components/gems/Gemfile
Signed-off-by: Ashique Saidalavi <ashique.saidalavi@progress.com>
In x64 machines the components for windows platforms are not installing due to mismatch  in platforms. Adding the x64 platforms so that these gems will be installed on x64 machines as well.
https://github.com/chef/kitchen-vcenter/pull/169
> Update the Ruby windows platforms for the components

- omnibus/config/software/rb-fsevent-gem.rb
If the rb-fsevent gem version noted in `components/gems/Gemfile.lock` is older than the HEAD of master branch in the repo referred in `omnibus/config/software/rb-fsevent-gem.rb`, then this results in a pre-compiled bundle plus recompiled bundle getting packaged in Chef Workstation. Some commands fail on MacOS. 
This is an attempt to maintain static reference to commit corresponding to the version noted in Gemfile.lock.
https://github.com/chef/chef-workstation/pull/2580
> attempt to keep rb-fsevent version in sync.

- .expeditor/update_docs_lints.sh
Signed-off-by: Kimberly Garmoe <kgarmoe@chef.io>
You'll need to manually update StylePath in `.vale.ini` to `docs-chef-io/<PRODUCT>/chef-web-docs/tools/vale` until someone has the time to sort out a better solution.
> Get docs lint config files, for precommit use

- omnibus/omnibus-test.ps1
Use Throw instead of Exit to ensure the CI job fails when a command has
a non-zero exit code.
Signed-off-by: Jeremiah Snapp <jeremiah@chef.io>
> Fix omnibus-test.ps1

- docs-chef-io/netlify.toml
Remove hugo and go version from netlify config. It's easier to set these parameters from the Netlify web UI and there's a bug in the current specified version that's breaking PR builds.
> Remove hugo and go version from netlify config

- docs-chef-io/content/workstation/troubleshooting.md
Signed-off-by: Sean Horn <horn@progress.com>
Restart CW Powershell for success
In CW Powershell, additions to the trusted_certs area can be unavailable without a restart.
Document that a restart may help.
https://getchef.zendesk.com/agent/tickets/27135
> Restart Chef Workstation Powershell for success

- .expeditor/config.yml
Due to build issues observed in few other products, the omnibus flag to ignore cache was set to TRUE. this slows down build  time. reverted the change so default value is used.
Successful ad hoc [build](https://buildkite.com/chef/chef-chef-workstation-main-omnibus-adhoc/builds/953) with setting restored to default.
https://github.com/chef/chef-workstation/pull/2460
> cached dependencies don't cause issue in workstation build

- omnibus/config/software/habitat.rb
This pull request was triggered automatically via Expeditor when habitat v. 1.6.521 was merged to main.
This change falls under the obvious fix policy so no Developer Certificate of Origin (DCO) sign-off is required.
The automated PR creation to update Habitat dependency failed earlier. Hence this manual script-run based PR.
> Bump habitat to 1.6.521

- omnibus/config/software/rb-fsevent-gem.rb
Need to manually update `rb-fsevent` commit hash to match version specified in Gemfile, to avoid notarize error. The `rb-fsevent` version got bumped in https://github.com/chef/chef-workstation/pull/2919
Related to https://github.com/chef/chef-workstation/pull/2637
> Update rb-fsevent SHA in sync with updated version in Gemfile

- .expeditor/release.omnibus.yml
- docs-chef-io/content/workstation/install_workstation.md
Ubuntu package is presently built on an Ubuntu 16.04 system. This package is usable on Ubuntu 18.04 & 20.04 as well. This pr will remove Ubuntu 16 from the supported platforms and add Ubuntu 22.04. The package has been now built with ubuntu 18.04. 
Adhoc build URL: https://buildkite.com/chef/chef-chef-workstation-main-omnibus-adhoc/builds/1239#018498b7-6660-4567-a7af-8e84a1bed67f
> Removed Ubuntu 16 and added support for Ubuntu 22.04

- omnibus/resources/chef-workstation/msi/source.wxs.erb
- src/workstation-gui/stopserver.ps1
Added custom action that invokes a script similar to `server.ps1` to kill the Rails server process only on uninstall. Earlier, the uninstall would not be a clean one as files in use by ruby process would not get deleted.
> Added Rails service stop when uninstalling on Windows

- omnibus/Gemfile.lock
An earlier dependabot PR [merge](https://github.com/chef/chef-workstation/commit/db304bcdcced1019d851fa197144abc5f2a938b6) removed mixlib-shellout UCRT dependency, as it runs on older bundler. Restoring same.
Failing build on Windows.
> restore dep inadvertantly removed in earlier dependabot merge

- omnibus/package-scripts/chef-workstation/postinst
- src/workstation-gui/poststeps.sh
Few cases covered in macOS install-
1. Create `~/Library/LaunchAgents` folder if not already present.
1. Use `$HOME` instead of `~` in filepaths.
1. Keep Chef Workstation App intact post-install so codesign check succeeds in Ventura.
https://github.com/chef/chef-workstation/issues/3019
https://github.com/chef/chef-workstation/issues/3021
> INFWS-175 Tweaks in post-install script

- docs-chef-io/content/workstation/chef-workstation-app.md
This reverts commit c3856390ccb36bef0e04a6ffaf6733d420aec1e3.
We removed the experimental feature in the most recent build 23.3.1030. Updating doc to remove note on same.
https://github.com/chef/chef-workstation-app/pull/745
> Revert documentation note #2954

- components/main-chef-wrapper/cmd/env.go
Redirected the --chef-license flow to the chef-cli for the chef env command.
#fixed: https://github.com/chef/chef-workstation/issues/3061
> FIxed the --chef-license issue

- components/gems/Gemfile.lock
The updated chef-cli gem has fix to the template creation warning.
https://github.com/chef/chef-cli/issues/219
> Update chef-cli version

- Dockerfile
Hi!
The Dockerfile placed at "Dockerfile" contains the best practice violation [DL3008](https://github.com/hadolint/hadolint/wiki/DL3008) detected by the [hadolint](https://github.com/hadolint/hadolint) tool.
The smell DL3008 occurs when the version pinning for the installed packages with apt is not specified. This could lead to unexpected behavior when building the Dockerfile.
In this pull request, we propose a fix for that smell generated by our fixing tool. We have verified that the patch is correct before opening the pull request.
To fix this smell, specifically, we use a heuristic approach that selects the most probable version tag for a given apt package corresponding to the latest version at the current date. The package versions are retrieved using the Canonical Launchpad APIs. …
> Fix for Dockerfile smell DL3008

- omnibus/Gemfile.lock
Ffi-yajl 2.6.0 is failing to install in Windows.
> Reverted ffi-yajl to 2.4.0

- components/gems/Gemfile
Added the RUBY_PLATFORM method to identify different windows platforms and installed these windows specific gems.
This will install the win32-security gem which was missing in installer in the latest chef-workstation version
https://chefio.atlassian.net/browse/CHEF-4143
> Updated condition for windows specific gems

- components/main-chef-wrapper/main.go
Updated the hardcoded path of  InstallerDir from `C:\opscode\chef-workstation` to fetch the actual InstallDirectory of the chef-workstation installation path across all platforms.
> Fixed the - Chef Workstation Errors When Running from D Drive - "exec... file does not exist"

- .expeditor/verify.pipeline.yml
Updating the ruby image to ruby:3.1-bullseye to overcome the thread error on verify pipelines. 
Ref: https://github.com/docker-library/golang/issues/467#issuecomment-1601845758
> Updated the ruby image to overcome the thread error

- docs-chef-io/Makefile
- docs-chef-io/go.mod
Update how Netlify deploys docs previews.
https://github.com/chef/chef-web-docs/pull/4255
https://chefio.atlassian.net/browse/CHEF-11081
> Update Netlify docs deploy method

- components/gems/Gemfile.lock
Because of Centos 7 EOL all workflows are broken: https://github.com/test-kitchen/kitchen-dokken/compare/v2.20.5...v2.20.6
> Bump kitchen-dokken to 2.20.6

- docs-chef-io/content/workstation/install_workstation.md
https://progresssoftware.atlassian.net/browse/CHEF-15020
> Remove references to packages.chef.io

- .expeditor/release.omnibus.yml
- omnibus/config/projects/chef-workstation.rb
* Add Macos 12 arm and X86-64 support
The Chef Workstation build for macOS 12   fails due to a critical error in the dep-selector-libgecode gem during compilation. Hence autoconf (2.69) and gecode (3.7.3)   added for mac platform.
Gecode 3.7.3’s build system is incompatible with autoconf ≥2.72.
Error: 
configure: error: cannot find required auxiliary files: config.guess config.sub
  | make: *** [Makefile:1457: config.status] Error 1
  | extconf.rb:124:in `block in run': Failed to build gecode library.
  | (GecodeBuild::BuildError)
  | from extconf.rb:123:in `chdir'
  | from extconf.rb:123:in `run'
  | from extconf.rb:130:in `<main>'
  |  
  | extconf failed, exit code 1
- Introduced conditional dependencies: autoconf and gecode for macOS
Log: …
> CHEF-20210 : Verified builds on both x86_64 and arm64 macOS 

- .expeditor/release.omnibus.yml
This PR updates the builder matrix to ensure that:
- The build is always performed on macOS 12 (arm64) for compatibility with the notarization process.
- Tests continue to run on macOS 12, 13, and 14 (arm64) to ensure broad compatibility.
> update Mac builder matrix to resolve notarization step failure
