chef/chef-workstation

- README.md
update readme to reflect chef-run
> update readme to reflect chef-run

- README.md
Removed the link.
Signed-off-by: JJ Asghar <jj@chef.io>
> Removed the nonexistent FAF

- README.md
Update readme to trigger build
> Update readme to trigger build

- omnibus/Gemfile.lock
https://github.com/chef/omnibus-software/pull/963/files will fix our
recent Unix build failures
N/A
> Updating omnibus-software definitions to take advantage of a bug fix

- .expeditor/config.yml
- CHANGELOG.md
[Please describe what this change achieves]
SHACK-304
> [SHACK-304] Do not update Chef Workstation changelog for ChefDK changes

- .expeditor/config.yml
Wait for chef-workstation-app merge_actions to finish.
> Wait for chef-workstation-app merge_actions to finish.

- omnibus/resources/chef-workstation/msi/localization-en-us.wxl.erb
- omnibus/resources/chef-workstation/msi/source.wxs.erb
The ChefDK message page is shown before the 'Click install to proceed' page when chefdk is installed - that's the final step before any system changes are applied.
> Uninstall ChefDK when installing CWS on Windows

- www/site/content/docs/chef-workstation/chef-workstation-app.md
> Adds the in-flight Chef Workstation App doc page

- omnibus/config/projects/chef-workstation.rb
This change adds conflic and replace for chefdk so that installing workstation will replace dk.
SHACK-371
> Upgrade on linux

- www/site/content/docs/chef-workstation/about.md
- www/site/content/docs/chef-workstation/chef-run-users-guide.md
- www/site/content/docs/chef-workstation/chef-workstation-app.md
> post-merge doc updates

- omnibus/resources/chef-workstation/pkg/welcome.html.erb
> Add tray to installer welcome text on mac.

- README.md
Signed-off-by: Stefan Wessels Beljaars <swesselsbeljaars@schubergphilis.com>
Fixes typo and expanded an example
> README updated: fixed typo and expanded an example

- www/site/content/docs/chef-workstation/getting-started.md
- www/site/content/docs/chef-workstation/install.md
- www/site/content/docs/reference/config.md
All links should now be relative. I also made download links use omintruck to
download directly.
- ~[ ] PR title is a worthy inclusion in the CHANGELOG~
> Fix two additional links to be relative

- .expeditor/buildkite/hugo_lint.sh
- .expeditor/config.yml
- .expeditor/verify.pipeline.yml
> Add verification testing; lint documentation

- .expeditor/update_chef-workstation-app_to_latest.sh
> Bug - expeditor pointing at wrong file

- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
This adds Code of Conduct and Contributing docs. 
(n/a)
> CoC and Contrib docs

- .expeditor/announce-release.sh
- .expeditor/publish-release-notes.sh
Expeditor injects the variables in all caps:
https://expeditor.chef.io/docs/reference/workloads/#environment-variables
https://expeditor.chef.io/docs/reference/workloads/#artifact
> Fix environment variables in release scripts

- omnibus/config/projects/chef-workstation.rb
> [ChefDK to 3.6.4] Add kitchen-ec2 support for arm64 architecture

- .expeditor/purge-cdn.sh
This was inadvertently missed as part of chef/chef-workstation#323
> Fix env var capitalization in purge-cdn.sh

- .expeditor/announce-release.sh
> Fixing expeditor failure - wrong variable capitalization

- docs/architecture/telemetry-seq.puml
- docs/architecture/telemetry.md
Design for telemetry service living in the CWA, allowing us to provide locally centralized telemetry handling.
> [SHACK-402] Design for local telemetry service

- www/site/content/docs/chef-workstation/chef-run-users-guide.md
Signed-off-by: Brad Dausses <brad.dausses@gmail.com>
Following on https://github.com/chef/chef-workstation/pull/78 this change aligns terminology to prevent confusion (which I personally encountered) on resource properties vs. attributes of a given CCR.
None.  Documentation change only.
> Updated attributes to properties in chef-run user guide

- .expeditor/verify.pipeline.yml
Uses new Expeditor DSL. 
[List any existing issues this PR resolves, or any Discourse or
StackOverflow discussion that's relevant]
> Leverage new Expeditor DSL for buildkite pipeline YAML

- omnibus/Gemfile.lock
- omnibus_overrides.rb
> Update omnibus and omnibus-software. Also, add pin for rust version.

- .github/CODEOWNERS
- .github/ISSUE_TEMPLATE/BUG_TEMPLATE.md
- .github/ISSUE_TEMPLATE/DESIGN_PROPOSAL.md
- .github/ISSUE_TEMPLATE/ENHANCEMENT_REQUEST_TEMPLATE.md
- .github/ISSUE_TEMPLATE/SUPPORT_QUESTION.md
- .github/PULL_REQUEST_TEMPLATE.md
- CODEOWNERS
> Add more github issue templates + fix the codeowners file

- omnibus/Gemfile.lock
- omnibus/omnibus-test.ps1
- omnibus/omnibus-test.sh
Minor improvements to new omnibus test script output.
Bump omnibus gem to latest version to be able to properly build macos packages in the new omnibus pipeline.
> Improvements to new omnibus pipelines

- omnibus/config/software/git-custom-bindir.rb
- omnibus/kitchen.yml
- omnibus/omnibus.rb
> Misc omnibus cleanup from DK

- omnibus/config/software/chef-dk-gem-versions.rb
- omnibus/files/chef-dk-gem-versions/default/installed_gems_as_json.rb
> Adding missing software definition for omnibus build

- ci/verify.bat
- ci/verify.sh
Keep until we sort out Buildkite issues
N/A
> Adding back Jenkins verification scripts temporarily to enable release

- omnibus/config/software/chef-dk.rb
This was fixed in DK, but never ported over to Workstation.
> Make sure we properly appbundler Chef and InSpec gems

- .expeditor/config.yml
- .expeditor/update_dockerfile.sh
- Dockerfile
We have one for dk. Even though on the CLI it's the same we should include that.
> Add a chefworkstation docker container

- omnibus/README.md
There were many things in this readme that were no longer true. I've updated the instructions by following them to the letter to see if they work.
> Update the omnibus readme to reflect reality

- omnibus/Gemfile.lock
- omnibus_overrides.rb
> Update rubygems to 3.0.4 and curl to 7.65.1

- .github/CODEOWNERS
- README.md
> Fix readme formatting and update the codeowners

- .expeditor/release.omnibus.yml
Signed-off-by: Jaymala Sinha <jsinha@chef.io>
> Enable RHEL 8 packages

- .expeditor/verify.pipeline.yml
- .gitignore
- Gemfile
- Rakefile
- components/gems/Gemfile
- components/gems/Rakefile
- omnibus/Berksfile
- omnibus/config/projects/chef-workstation.rb
- omnibus/config/software/chef-workstation-app.rb
- omnibus/config/software/gems.rb
- omnibus/config/software/nodejs-binary.rb
- omnibus/config/software/uninstall-scripts.rb
- omnibus/cookbooks/chef-workstation-builder/attributes/default.rb
- omnibus/cookbooks/chef-workstation-builder/metadata.rb
- omnibus/cookbooks/chef-workstation-builder/recipes/default.rb
- omnibus/files/chef-dk-env-customization/windows/chefdk_env_customization.rb
- omnibus/files/rubygems-customization/windows/operating_system.rb
Wire up chefstyle testing and add a rakefile for the style task.
> Wire up Chefstyle in Buildkite

- .expeditor/config.yml
- .expeditor/update_dep.sh
This automatically updates the bundled gems when they have an update.
> Move ChefDK gem bumping logic to Chef Workstation

- components/gems/Gemfile
- components/gems/Gemfile.lock
> Update Chef to 15.2.20

- omnibus/config/projects/chef-workstation.rb
> Begin signing MSI's with renewed Windows Signing Cert

- .expeditor/release.omnibus.yml
- omnibus/Gemfile.lock
- omnibus_overrides.rb
Signed-off-by: Jaymala Sinha <jsinha@chef.io>
> Deprecate macOS 10.12 and add macOS 10.15 support

- .expeditor/config.yml
- components/gems/Gemfile
- components/gems/Gemfile.lock
- omnibus/Gemfile.lock
- omnibus/verification/spec/unit/verify_spec.rb
- omnibus/verification/verify.rb
> Updating gems to non-yanked versions

- .expeditor/publish-release-notes.sh
Pushing the release notes failed
N/A
> Updating github auth in Expeditor to match expected behavior

- omnibus/Gemfile.lock
We need Go 💯 for https://github.com/chef/chef-workstation/pull/553
> Updates omnibus-software to have Go

- omnibus/package-scripts/chef-workstation/postinst
- omnibus/resources/chef-workstation/msi/localization-en-us.wxl.erb
- omnibus/resources/chef-workstation/pkg/welcome.html.erb
It's time to remove the experimental word here
> Stop calling the workstation toolbar experimental

- omnibus/verification/verify.rb
From https://github.com/chef/chef-workstation/pull/570 we needed to update this.
TODO: Create a more realistic `fauxhai-ng` test!
> Update omnibus tests to unblock pipeline

- omnibus/verification/spec/unit/verify_spec.rb
I think we should have left the tests from this PR run https://github.com/chef/chef-workstation/pull/577
> Fix pipeline: Take 2

- components/main-chef-wrapper/main.go
> Removes the analyze command from the help message

- components/gems/Gemfile.lock
This finds various names of the chef cli so it doesn't fail in the
policyfiles runs
> Update Test Kitchen to 2.3.4

- omnibus/Gemfile.lock
> Update omnibus deps to the latest

- components/gems/Gemfile.lock
> Update chef-apply to 0.4.11

- omnibus/verification/component_test.rb
- omnibus/verification/verify.rb
Minor cleanup and removal of old backwards compat code
> Minor updates to the build verification code

- components/gems/Gemfile.lock
- omnibus/Gemfile.lock
> Update knife-windows and knife-azure

- components/gems/Gemfile.lock
- omnibus/Gemfile.lock
Roll out require_relative to more projects
> Update mixlib-log, mixlib-archive, ffi-yajl, knife-ec2, wmi-lite and mixlib-config

- components/gems/Gemfile.lock
- omnibus/Gemfile.lock
New versions that use require_relative for perf improvements.
> Update chef-zero, mixlib-authentication, mixlib-install, mixlib-versioning, and mixlib-shellout

- components/gems/Gemfile
- components/gems/Gemfile.lock
> Update chef-vault to 4.0.1

- omnibus/Gemfile.lock
- omnibus/config/software/git-custom-bindir.rb
This resolves multiple CVEs in git.
> Update git to 2.24.1

- components/gems/Gemfile.lock
> Update knife-ec2 to 1.0.28

- omnibus/Gemfile
- omnibus/Gemfile.lock
Now that notarization changes have shipping in omnibus and omnibus-software update to point at released/master versions.
> Update omnibus and omnibus-software

- components/gems/Gemfile.lock
> Update Cookstyle to 5.20

- components/gems/Gemfile
- components/gems/Gemfile.lock
> Update knife-google to 4.2.7

- components/gems/Gemfile.lock
This swaps logify for mixlib-log
> Update to chef-api 0.10.5

- components/gems/Gemfile.lock
- omnibus/Gemfile.lock
> Update knife-vsphere and win32-service deps

- omnibus/config/projects/chef-workstation.rb
This PR fixes our ad hoc builds for macOS.
N/A
> omnibus:(project) update build_version

- components/gems/Gemfile.lock
> Update knife-windows to 3.0.13

- components/gems/Gemfile.lock
We have verifiers for Debian 10 now
> Update knife-acl to 1.0.8

- components/gems/Gemfile.lock
- omnibus/Gemfile.lock
omnibus-software unbreaks our builds
> Update chef-apply and omnibus

- components/gems/Gemfile.lock
Also bumping minor version for scheduled release
N/A
> Pinning bundler back to 1.x to fix builds

- .expeditor/release.omnibus.yml
This PR just adds a Windows 10 tester and has been verified to work in this adhoc build:
https://buildkite.com/chef/chef-chef-workstation-master-omnibus-adhoc/builds/216
Signed-off-by: Christopher A. Snapp <csnapp@chef.io>
> Add Windows 10 Tester

- .expeditor/config.yml
> Forgot to perform release build on version bump

- omnibus/Gemfile.lock
Signed-off-by: Jaymala Sinha <jsinha@chef.io>
Update omnibus-software for new msys2 path
> Update omnibus-software for new msys2 path

- .expeditor/config.yml
Only maintaining this pipeline temporarily while we get the 20.x GA
release fully tested. After a few 20.x releases and we have confidence
in that we should delete this other pipeline.
> Setting up Expeditor 0.18 pipeline for releasing

- www/layouts/shortcodes/ws_knife_configure_summary.md
Fix a couple bad links in the docs.
> fix a couple bad links

- .expeditor/config.yml
Chef 16 was also released so we should subscribe to those update
notifications.
#1158
> Adding project alias in Expeditor

- .expeditor/create_pr_for_homebrew.sh
- .expeditor/publish_to_chocolatey.ps1
- .expeditor/third-party-packages.pipeline.yml
Pull in homebrew support from https://github.com/chef/chef-workstation/pull/1147
Add retry logic to chocolatey because omnitruck takes a bit to update
> Adding homebrew support and fixing chocolatey support

- components/gems/Gemfile.lock
- omnibus/Gemfile.lock
Update the kitchen drivers to the latest
> Update Test Kitchen, kitchen-ec2, and kitchen-hyperv

- .expeditor/config.yml
- components/gems/Gemfile.lock
Also update the subscription for auto PR generation
> Update Fauxhai to 8.2

- components/gems/Gemfile.lock
> Update knife-windows to 3.0.17

- components/gems/Gemfile.lock
> Update kitchen-digitalocean to 0.11

- omnibus/Gemfile.lock
Consume https://github.com/chef/omnibus-software/pull/1201
> Consuming Ruby 2.7.1 performance fix patch

- components/gems/Gemfile
- components/gems/Gemfile.lock
This incldues 2 knife bootstrap regression fixes
> Update Chef Infra Client to 16.1.16

- www/content/workstation/upgrade_lab.md
- Rename page from upgrade_labs -> upgrade_lab
- Add upgrade_labs alias
> Rename upgrade_labs, add alias

- www/content/workstation/upgrade_lab.md
> Fix reference to "chef analyze report" in upgrade lab

- omnibus/config/software/rb-fsevent-gem.rb
This ensure we don't install conflicts, EG:
```
Unable to activate chef-cli-3.0.11, because diff-lcs-1.4.3 conflicts with diff-lcs (>= 1.0, < 1.4) (Gem::ConflictError)
```
Closes https://github.com/chef/chef-workstation/pull/1303
> Ignore rb-fsevent dependencies when rebuilding it

- components/gems/Gemfile
- components/gems/Gemfile.lock
> Bump Chef Infra Client to 16.2.73

- .expeditor/config.yml
> Temporarily comment out our docker builds while our backend gets updated

- .expeditor/publish_to_chocolatey.ps1
> Chocolatey times out too much, lets add some debugging info

- omnibus/Gemfile.lock
- omnibus/config/software/more-ruby-cleanup.rb
- omnibus_overrides.rb
> Bump omnibus software again and bump library deps

- .expeditor/build.docker.yml
- .expeditor/config.yml
- Dockerfile
- dobi.yaml
Following the instructions from
https://expeditor.chef.io/docs/pipelines/docker/ and looking at the
Chef config.
Fixes https://github.com/chef/chef-workstation/issues/1402
> Reenabling Docker image builds using Dobi

- components/gems/Gemfile
- components/gems/Gemfile.lock
- omnibus/Gemfile.lock
- omnibus/package-scripts/chef-workstation/postinst
- omnibus/package-scripts/chef-workstation/postrm
- omnibus_overrides.rb
Bundling some other dependency update PRs to make releasing faster.
> Release prep

- components/gems/Gemfile
- components/gems/Gemfile.lock
Also bump the minimums for other libs to speed up depsolving
> Update Chef Infra Client to 16.5

- components/main-chef-wrapper/main.go
From https://github.com/chef/chef-cli/pull/133
> Copying patent notice into wrapper

- components/gems/Gemfile.lock
This ensures we load yaml correctly and includes several performance
improvements
> Update Test Kitchen to 2.7.2

- docs-chef-io/content/workstation/config_rb.md
- docs-chef-io/content/workstation/config_rb_optional_settings.md
- docs-chef-io/content/workstation/ctl_push_jobs_client.md
- docs-chef-io/content/workstation/knife_azure.md
- docs-chef-io/content/workstation/knife_azurerm.md
- docs-chef-io/content/workstation/knife_bootstrap.md
> node name -> unique identifier

- omnibus/Gemfile.lock
> Bumping omnibus and omnibus-software to get new cacerts

- docs-chef-io/content/workstation/config_yml_kitchen.md
> Fix a few Test Kitchen docs

- RELEASE_PROCESS.md
Documenting the release process for Chef Workstation
Aha! Link: https://chef.aha.io/features/SH-449
> Inital release process documentation

- omnibus/config/software/habitat.rb
Signed-off-by: Collin McNeese <cmcneese@chef.io>
Current workstation release is using older Habitat version `1.6.56`.  This bumps to include the current stable release for new features and fixes which are included in `1.6.181`
> Updates included Habitat to 1.6.181 from 1.6.56

- docs-chef-io/content/workstation/install_workstation.md
Also cleanup some markdown warnings
> Update the docs for supported platforms

- omnibus/Gemfile.lock
This fixes the windows git sha
> Update omnibus-software to resolve windows builds

- omnibus/Gemfile.lock
- omnibus_overrides.rb
Pull in the latest and greatest
> Update libiconv and libarchive to the latest

- components/gems/Gemfile.lock
> Bump kitchen-inspec to 2.2.2

- docs-chef-io/content/workstation/getting_started.md
-  The "Create .chef Directory" section has been removed from the Getting Started page.
- Minor fixes in the Getting Started Document
- https://github.com/chef/chef-workstation-app/pull/275
- https://github.com/chef/chef-workstation/issues/1588
> Chef directory update

- .expeditor/config.yml
Let's not spend the $$$ running that whole pipeline
> Don't create a build / bump version for docs

- docs-chef-io/content/workstation/_index.md
- Remove the mention of DK being maintained
- Remove Ruby as an included tool
- Remove Delivery as an included tool
- Rework how you test to not mention chef infra server
> Update the workstation description

- docs-chef-io/content/workstation/upgrade_lab.md
This is not a high-level thing the way we organize Workstation. It's a feature/tool of workstation
> Move Upgrade Lab under tools menu

- docs-chef-io/content/workstation/config_rb.md
- docs-chef-io/content/workstation/knife_setup.md
Adds basic setup information to knife_setup.md. Formatting fixes on config_rb.md
We should tell people how configure knife.
Aha! Link: https://chef.aha.io/features/SH-2017
> How to set up knife

- omnibus/resources/chef-workstation/pkg/welcome.html.erb
It's a thing we ship. We should mention it.
> Add Habitat to the installer info page

- docs-chef-io/content/workstation/chefspec.md
- docs-chef-io/content/workstation/install_workstation.md
- omnibus/kitchen.yml
Stop talking about soon to be EOL Ubuntu 16.04
We already nuked RHEL 6 from workstation
> Update docs and omnibus script to match supported platforms

- docs-chef-io/content/workstation/install_workstation.md
> Update the versions in the install example

- .expeditor/config.yml
Trigger just on InSpec to avoid the inspec, inspec-core and inspec-bin
PR
> Prevent duplicate inspec bump PRs

- docs-chef-io/content/workstation/chef_vault.md
- docs-chef-io/content/workstation/foodcritic.md
> Recipe DSL -> Chef Infra Language

- docs-chef-io/content/workstation/ctl_kitchen.md
Signed-off-by: Vasu1105 <vasundhara.jagdale@chef.io>
> Fix the url path causing Page not found error

- components/gems/Gemfile
- components/gems/Gemfile.lock
> Update Chef Infra Client to 16.9.20

- omnibus/Gemfile.lock
> Update omnibus-software again for libarchive fixes

- docs-chef-io/content/workstation/install_workstation.md
The install page needed a wget example for RHEL/
> Add RHEL example

- .expeditor/release.omnibus.yml
- omnibus/config/software/git-custom-bindir.rb
We want Workstation to be used in pipelines so make sure we can use it
in everyone's pipeline
> Product Amazon Linux 2 packages

- components/packaging/chocolatey/chef-workstation.nuspec
- omnibus/README.md
- omnibus/config/projects/chef-workstation.rb
- omnibus/config/software/chef-analyze.rb
- omnibus/config/software/chef-automate-collect.rb
- omnibus/config/software/chef-workstation-app.rb
- omnibus/config/software/gem-version-manifest.rb
- omnibus/config/software/gems.rb
- omnibus/config/software/git-custom-bindir.rb
- omnibus/config/software/habitat.rb
- omnibus/config/software/main-chef-wrapper.rb
- omnibus/config/software/more-ruby-cleanup.rb
- omnibus/config/software/nodejs-binary.rb
- omnibus/config/software/powershell-scripts.rb
- omnibus/config/software/preparation.rb
- omnibus/config/software/rb-fsevent-gem.rb
- omnibus/config/software/ruby-windows-system-libraries.rb
- omnibus/config/software/rubygems-customization.rb
- omnibus/config/software/uninstall-scripts.rb
- omnibus/config/software/windows-env-customization.rb
- omnibus/files/openssl-customization/windows/ssl_env_hack.rb
- omnibus/kitchen.yml
Minor cleanup of the omnibus configs
> Update license/copyright headers in omnibus + kitchen config

- .expeditor/config.yml
- components/gems/Gemfile.lock
Also make sure these PRs happen automatically in the future.
> Update kitchen-openstack to 6.0

- docs-chef-io/content/workstation/getting_started.md
> Clarify why we don't setup ruby on Windows

- docs-chef-io/content/workstation/install_workstation.md
Minor updates to how to install the application
> Updates to the installation instructions

- components/gems/Gemfile
- components/gems/Gemfile.lock
We can tighten these up as we need to, but there's no point at the
moment
> Loosen deps and raise the floors

- omnibus/config/software/git-custom-bindir.rb
Pull in the latest git version
> Bump git to 2.30.1

- docs-chef-io/content/workstation/getting_started.md
Fix heading in getting started doc.
Currently this is an H1 heading which doesn't show up in our TOC. This makes it an H2.
> Fix heading 

- omnibus/package-scripts/chef-workstation/postinst
Make it more clear that if they don't have a GUI they don't care about doing this.
> Better describe what the workstation app is on Linux

- docs-chef-io/content/workstation/install_workstation.md
> Update docs for the new upgrade behavior

- docs-chef-io/content/workstation/getting_started.md
See #1740 for context. Breaks out the repository setup changes.
> Update Chef Infra repository setup

- docs-chef-io/content/workstation/_index.md
- docs-chef-io/content/workstation/config.md
- docs-chef-io/content/workstation/getting_started.md
- docs-chef-io/content/workstation/install_workstation.md
- docs-chef-io/content/workstation/privacy.md
- docs-chef-io/content/workstation/troubleshooting.md
Changes in the nav names and styling since the consolidation made this section difficult to follow.  This PR reweights the pages in the top WS headers. The tools section lives in a different config and will be moved in a chef-web-docs pr.
Question: Should `Troubleshooting` become `Troubleshoot`? It is consistent with the style but may be unusual to users. Opinions?
> Simplify and order nav

- docs-chef-io/content/workstation/install_workstation.md
This is a good way to make sure folks stay up to date
> Document installing workstation via choco

- omnibus/config/software/git-custom-bindir.rb
> Update Embedded git to 2.30.2

- docs-chef-io/content/workstation/getting_started.md
We already describe what this is outside the tabs
> Remove the duplicate description from the path setup

- omnibus/config/software/habitat.rb
> Add missing linux/windows shas for Hab

- components/gems/Gemfile.lock
- omnibus/Gemfile.lock
> Update curl to resolve 2 CVEs

- omnibus/config/software/git-custom-bindir.rb
Signed-off-by: Nikhil Gupta <nikhilgupta2102@gmail.com>
Updated Git to 2.31.1
Fixes. [https://github.com/chef/chef-workstation/issues/1907](url)
> updated Git to 2.31.1

- omnibus/Gemfile.lock
> Bump omnibus and omnibus-software

- dobi.yaml
Be explicit about when to apply the channel and latest tags.
Signed-off-by: Tom Duffield <github@tomduffield.com>
> Update Dobi annotations to address tagging bug

- omnibus_overrides.rb
> Pin go to 1.13.1 for now to fix failures

- .expeditor/release.omnibus.yml
> Update the macos 11 config in the omnibus pipeline

- docs-chef-io/content/workstation/getting_started.md
- docs-chef-io/content/workstation/install_workstation.md
- docs-chef-io/content/workstation/setup.md
Clarify the things you need to get started
> Fix the setup page title / clarify needs

- docs-chef-io/content/workstation/install_workstation.md
- docs-chef-io/content/workstation/setup.md
> Fix relref in docs

- docs-chef-io/content/workstation/getting_started.md
A new pagename led to link problems.
> Revert filename to fix link problems

- components/gems/Gemfile
- components/gems/Gemfile.lock
> Update ChefSpec to 9.3 and update minimum versions

- docs-chef-io/content/workstation/install_workstation.md
Signed-off-by: Ian Maddaus <Ian.Maddaus@progress.com>
Fix a bad link in the install_workstation.md page.
> Fix bad link

- .gitignore
- omnibus/config/software/more-ruby-cleanup.rb
- omnibus/verification/spec/unit/verify_spec.rb
- omnibus/verification/verify.rb
Signed-off-by: Pranay Singh <i5singh.pranay@gmail.com>
Allows compatible version of curl to get compiled in chef worksation
fixes https://github.com/chef/chef-workstation/issues/1840
> Adding test for curl cli

- .expeditor/update_habitat.sh
Signed-off-by: Jeff Stasko <jrstasko@gmail.com>
This will properly update the linux and windows shas now. 
#1879
> update to properly find edit linux and windows shas

- omnibus/config/software/gems.rb
- omnibus/config/software/rb-fsevent-gem.rb
This reverts commit 8470fbe376b8f0536dc288a6159d39108d73da1e.
> Revert "Remove the omnibus install of rb-fsevent"

- omnibus/verification/spec/unit/verify_spec.rb
- omnibus/verification/verify.rb
> Fix curl test

- docs-chef-io/content/workstation/knife_configure.md
We updated this to match the new behavior
> knife configure actually creates a credentials file

- docs-chef-io/content/workstation/getting_started.md
We were using the wrong words here.
> Certificate -> Private Key in setup

- docs-chef-io/content/workstation/knife_setup.md
> Remove some incorrect information on setting up knife

- docs-chef-io/content/workstation/config_yml_kitchen.md
- docs-chef-io/content/workstation/knife_search.md
Part of https://github.com/chef/chef-web-docs/issues/2831
> Remove mentions of Ubuntu 16.04

- docs-chef-io/content/workstation/getting_started.md
It turns out this works and is much simpler to describe.
> Update setup instructions to use knife configure

- components/gems/Gemfile.lock
> Update Chef Infra Client to 17.2

- docs-chef-io/content/workstation/install_workstation.md
You would not have a good time at all with 2GB
> Use more reasonable ram/disk requirements

- .expeditor/release.omnibus.yml
> Enable FIPS on Ubuntu builds

- components/gems/Gemfile
- components/gems/Gemfile.lock
> Update Test Kitchen to 3.0

- components/chef-automate-collect/habitat/plan.ps1
- components/chef-automate-collect/habitat/plan.sh
> Fix typos in the habitat plans

- components/gems/Gemfile.lock
> Update Chef Infra Client to 17.4.25

- components/gems/Gemfile.lock
> Bump chef to 17.4.38

- .expeditor/config.yml
Signed-off-by: Tom Duffield <github@tomduffield.com>
> Manually specify promotion actions in Expeditor

- docs-chef-io/content/workstation/plugin_knife_custom.md
Signed-off-by: Dishank Tiwari <dtiwari@progress.com>
Update /master/ to /main/ across the documentation.
> Replaced /main/ from /master/

- .expeditor/release.omnibus.yml
Debian 11
macOS 12
Windows 2022
Windows 11
Ubuntu 16.04 (it's back!)
> Add more platforms

- docs-chef-io/content/workstation/install_workstation.md
> Update the list of supported platforms

- CHANGELOG.md
Updated to mention latest stable release `21.10.640`
> Manually updating commits

- .expeditor/create_pr_for_homebrew.sh
brew command was failing due to use of obsolete `cask` subcommand.
https://github.com/chef/chef-workstation/issues/2325
> Fix brew command syntax

- .expeditor/create_pr_for_homebrew.sh
10.14 packages are not a thing anymore
> Update homebrew package promotion

- docs-chef-io/netlify.toml
> Bump hugo to 0.91.2

- docs-chef-io/content/workstation/install_workstation.md
- docs-chef-io/content/workstation/upgrade_lab.md
> Downloads links

- .github/dependabot.yml
> Setup dependabot for go deps

- .expeditor/release.omnibus.yml
- .expeditor/update_habitat.sh
- omnibus/config/software/habitat.rb
Signed-off-by: Ashwin <avarma@msystechnologies.com>
- Updated the Habitat packaging scripts to include aarch64 habitat [package](https://packages.chef.io/files/stable/habitat/latest/hab-aarch64-darwin.zip) & its [sha256sum](https://packages.chef.io/files/stable/habitat/latest/hab-aarch64-darwin.zip.sha256sum)
update_habitat.sh
habitat.rb
https://github.com/chef/chef-workstation/issues/2396
> Worked on including habitat package in M1 bundling.

- dev-docs/README.md
Fixed URLs to docs and release process markdown.
> Fix URLs to docs and release process markdown

- .expeditor/update_chef-workstation-app_to_latest.sh
- omnibus/config/software/chef-workstation-app.rb
Signed-off-by: nikhil2611 <nikhilgupta2102@gmail.com>
Added the architecture in the source URL for the ws-app.
> Added the arch extension for the ws-app

- .expeditor/update_chef-workstation-app_to_latest.sh
- omnibus/config/software/chef-workstation-app.rb
Signed-off-by: nikhil2611 <nikhilgupta2102@gmail.com>
Added the sha1  for window and linux.
> Added the sha1  for window and linux

- docs-chef-io/content/workstation/knife.md
- docs-chef-io/content/workstation/knife_azurerm.md
- docs-chef-io/content/workstation/knife_windows.md
- docs-chef-io/content/workstation/plugin_knife_custom.md
> Fix dead links in docs

- docs-chef-io/content/workstation/config_rb.md
We support it if people pay for it.
> Update docs to call out Ubuntu supporting fips

- components/main-chef-wrapper/cmd/report.go
Signed-off-by: Pranay Singh <i5singh.pranay@gmail.com>
Chef report cookbook now works with -p flag
Fixes https://github.com/chef/chef-workstation/issues/2560
> Fix Chef report cookbook with -p flag

- .expeditor/update_docs_lints.sh
Signed-off-by: kagarmoe <kimberly.garmoe@progress.com>
> mdl config script fix

- .expeditor/update_docs_lints.sh
Signed-off-by: kagarmoe <kimberly.garmoe@progress.com>
> Get specific config file

- docs-chef-io/Makefile
Updates the docs makefile to handle changes made to chef-web-docs.
> Update docs makefile

- docs-chef-io/content/workstation/knife_client.md
Remove extra periods from knife_client.md
See here:
https://docs.chef.io/workstation/knife_client/#create
> Remove extra periods from knife_client.md

- omnibus/config/software/chef-workstation-app.rb
Signed-off-by: nikhil2611 <nikhilgupta2102@gmail.com>
Added the sha1 for linux and windows platform  and version for the workstation-app
> Added the sha1 and the latest ws-app version

- docs-chef-io/content/workstation/getting_started.md
'Setup' becomes 'set up' when it's a verb.  Like 'shut down', 'stand up', 'back up', 'stick up', 'log in' and 'log out'.
Spelling nit.
> Fix spelling

- omnibus/Gemfile.lock
Uses new omnibus Windows builders.
Signed-off-by: Jeremiah Snapp <jeremiah@chef.io>
> Update omnibus and omnibus-software in Gemfile.lock

- omnibus/Gemfile.lock
As described in https://github.com/chef/chef-workstation/blob/main/RELEASE_PROCESS.md have run `bundle update` and these changes built successfully in ad hoc build - https://buildkite.com/chef/chef-chef-workstation-main-omnibus-adhoc/builds/917
> Update dependencies based on `bundle update` run

- components/gems/Gemfile
Signed-off-by: Ashique Saidalavi <ashique.saidalavi@progress.com>
This PR is to bundle the `knife-vrealize` plugin with the chef workstation.
> INFCT-76 - Add knife-vrealize to workstation

- omnibus/Gemfile.lock
Also updated few other gem versions by running `bundle update`
> bump berkshelf in sync with components/gems

- docs-chef-io/content/workstation/kitchen.md
- docs-chef-io/layouts/shortcodes/chef-workstation/test_kitchen.md
Fix one shortcode instance. It's also used in `chef-web-docs/content`.
#2830
https://chefio.atlassian.net/browse/CHEFDOCS-189
> Shortcode fix

- omnibus/files/rubygems-customization/windows/operating_system.rb
Signed-off-by: nikhil2611 <nikhilgupta2102@gmail.com>
Removed the warning for windows platform
> Removed the warning for windows platform

- docs-chef-io/content/workstation/kitchen.md
The code sample in this shortcode isn't rendering properly. See https://docs.chef.io/workstation/kitchen/#work-with-proxies
This will fix it.
> Fix shortcode in kitchen doc

- docs-chef-io/content/workstation/ctl_chef.md
> Clarify metadata values in chef generate cookbooks

- omnibus/config/projects/chef-workstation.rb
Signed-off-by: Thomas Powell <powell@progress.com>
Update signing identity to unblock that portion of the builds.
- [X ] All commits have been signed-off for [the Developer Certificate of Origin](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco).
> Update signing identity

- src/workstation-gui/.gitignore
Signed-off-by: Sachin <sachin.jain@chef.io>
Update .gitinore file
- [] All new and existing tests passed.
> Update .gitignore file

- src/workstation-gui/app/controllers/api/v1/authentication_controller.rb
- src/workstation-gui/app/controllers/api/v1/cookbooks_controller.rb
- src/workstation-gui/app/controllers/api/v1/recipes_controller.rb
- src/workstation-gui/app/controllers/api/v1/repositories_controller.rb
- src/workstation-gui/app/controllers/api_v1_controller.rb
- src/workstation-gui/app/controllers/application_controller.rb
- src/workstation-gui/config/routes.rb
- src/workstation-gui/server.ps1
Updated the API namespace
Updated the logic to find the installation directory in windows.
> Auth API refactoring

- docs-chef-io/content/workstation/config_rb_optional_settings.md
- docs-chef-io/content/workstation/getting_started.md
Correct a bunch of docs typos and fix a few links.
> Fix a bunch of typos and a few bad links

- docs-chef-io/content/workstation/config.md
Minor typo correction. See under here: https://docs.chef.io/workstation/config/#location
> Minor correction on config.md

- docs-chef-io/content/workstation/ctl_chef.md
- docs-chef-io/layouts/shortcodes/chef-workstation/ctl_chef_install.md
- docs-chef-io/layouts/shortcodes/chef-workstation/ctl_chef_undelete.md
> Fix a few docs typos

- omnibus/config/software/chef-workstation-app.rb
Chef Workstation App version with entitlements updated to work on macOS Ventura
> Update chef-workstation-app version

- docs-chef-io/content/workstation/chefspec.md
Adjust the link pointing at the repo's examples directory
Signed-off-by: Sean Horn <sean_horn@opscode.com>
> Documentation: ChefSpec Assigned to Progress Chef Ownership

- components/gems/Gemfile.lock
- omnibus/Gemfile.lock
- src/workstation-gui/Gemfile.lock
Update includes chef-vault support for `client_key_contents` attribute in `~/.chef/credentials` file based profiles.
> Update chef-vault with support for client_key_contents

- omnibus_overrides.rb
Update openssl version for mac os to 1.1.1t from 1.1.1m and unpin  openssl ver- 1.0.2zb for other platform .
> Update openssl version for Mac os and unpin for other platforms

- .github/workflows/sonarqube.yml
- sonar-project.properties
Added the build file to Sonar Scan and properties file for the validation with SonarQube
> Added the build and properties for SonarQube

- components/gems/Gemfile.lock
Includes a minor fix in cookstyle.
> Update cookstyle version

- .expeditor/update_dep.sh
Introduced 'delete branch' as a preparatory step so if the branch exists from previous failed run on agent, it is cleared.
> Fix expeditor dependency update PR creation script

- .expeditor/release.omnibus.yml
Add support for RHEL-9 vis natively built package on this OS version.
Ad-hoc [build](https://buildkite.com/chef/chef-chef-workstation-main-omnibus-adhoc/builds/1414) tested.
> Add RHEL-9 native package

- components/gems/Gemfile.lock
Update knife to 18.2.7 in sync with bundled Chef Infra Client version.
> Update knife version

- .expeditor/config.yml
- omnibus/config/software/gems.rb
Few references were omitted in earlier [PR](https://github.com/chef/chef-workstation/pull/3049). This caused the omnibus based build to fail. Updated now. Successfully [built](https://github.com/chef/chef-workstation/pull/3049) and ad hoc package to validate.
> Update pending fauxhai-chef references

- components/gems/Gemfile.lock
Manually updated as expeditor script is failing.
> Update chef-apply version

- docs-chef-io/content/workstation/install_workstation.md
Update supported platforms in install page.
See chef/chef-web-docs#4111
> Update supported platforms

- components/gems/Gemfile.lock
Updated the berkshelf gem to latest 8.0.7 in components/gems/gemfile.lock
> Updated berkshelf to latest

- docs-chef-io/content/workstation/install_workstation.md
- docs-chef-io/content/workstation/upgrade_lab.md
Replace download links in Workstation docs from chef.io/downloads/tools/<something> to chef.io/downloads.
https://chefio.atlassian.net/browse/CHEF-3471
> CHEF-3450 Replace download links

- docs-chef-io/content/workstation/install_workstation.md
I missed one link in #3134
https://chefio.atlassian.net/browse/CHEF-3471
> CHEF-3450 Repace download link

- components/gems/post-bundle-install.rb
- omnibus/config/software/gems.rb
- post-bundle-install.rb
Added a `post-bundle-install.rb` script which will help to build and install gems from git repos.
https://chefio.atlassian.net/browse/CHEF-5877
> Build and Install gems from git repos

- components/gems/Gemfile.lock
- omnibus/Gemfile.lock
Bump the chef-cli rubygem dependency version to 5.6.14
> Updated the chef-cli version to 5.6.13

- omnibus/config/projects/chef-workstation.rb
This PR will update the msi signing method for the windows platforms.
> Updated the msi signing method

- .expeditor/create_pr_for_homebrew.sh
- RELEASE_PROCESS.md
- docs-chef-io/content/workstation/install_workstation.md
- docs-chef-io/content/workstation/reusable/md/workstation_supported_derived_platforms.md
- docs-chef-io/content/workstation/reusable/md/workstation_supported_platforms.md
Removed the references of EOL MacOS 10.15 from:
* Supported platforms in doc
* Script to create the homebrew pr
* Release process doc
> Removed the references of MacOS 10.15

- docs-chef-io/content/workstation/install_workstation.md
updated doc with the current updated versions
> updated doc with the current updated versions

- docs-chef-io/content/workstation/install_workstation.md
- #3281
- chef/chef-web-docs#4316
- [CHEF-15020](https://progresssoftware.atlassian.net/browse/CHEF-15020)
[CHEF-15020]: https://chefio.atlassian.net/browse/CHEF-15020?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Correct download APIs

- docs-chef-io/go.mod
Updated go.mod for protobuf version
> Updated go.mod for protobuf version

- .github/workflows/sonarqube.yml
- .github/workflows/unit.yml
Fixing Workflow does not contain permissions warnings, This PR fixes the following security issues:
https://github.com/chef/chef-workstation/security/code-scanning/18
https://github.com/chef/chef-workstation/security/code-scanning/17
> Fixing Workflow does not contain permissions warnings

- components/gems/Gemfile.lock
- omnibus/Gemfile.lock
Dependabot warning security fixes, It will fix below warnings -
https://github.com/chef/chef-workstation/security/dependabot/103
https://github.com/chef/chef-workstation/security/dependabot/102
https://github.com/chef/chef-workstation/security/dependabot/104
> Dependabot warning security fixes

- docs-chef-io/content/workstation/chef_vault.md
Describe chef-vault refresh command
> CHEF-22524 Describe chef-vault refresh command 

- docs-chef-io/content/workstation/reusable/md/workstation_supported_platforms.md
Update Workstation supported platforms in docs
> Update supported platforms in docs
